/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AddTeamMemberRequest
 */
export interface AddTeamMemberRequest {
    /**
     * 
     * @type {string}
     * @memberof AddTeamMemberRequest
     */
    userId: string;
    /**
     * 
     * @type {boolean}
     * @memberof AddTeamMemberRequest
     */
    isLead?: boolean;
}

/**
 * Check if a given object implements the AddTeamMemberRequest interface.
 */
export function instanceOfAddTeamMemberRequest(value: object): value is AddTeamMemberRequest {
    if ((!('userId' in value) && !('user_id' in value)) || (value['userId'] === undefined && value['user_id'] === undefined)) return false;
    return true;
}

export function AddTeamMemberRequestFromJSON(json: any): AddTeamMemberRequest {
    return AddTeamMemberRequestFromJSONTyped(json, false);
}

export function AddTeamMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddTeamMemberRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'isLead': json['is_lead'] == null ? undefined : json['is_lead'],
    };
}

export function AddTeamMemberRequestToJSON(json: any): AddTeamMemberRequest {
    return AddTeamMemberRequestToJSONTyped(json, false);
}

export function AddTeamMemberRequestToJSONTyped(value?: AddTeamMemberRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'is_lead': value['isLead'],
    };
}

