/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AgentVersion
 */
export interface AgentVersion {
    /**
     * 
     * @type {string}
     * @memberof AgentVersion
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AgentVersion
     */
    agentId: string;
    /**
     * 
     * @type {string}
     * @memberof AgentVersion
     */
    versionLabel: string;
    /**
     * 
     * @type {boolean}
     * @memberof AgentVersion
     */
    competitionEligible: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AgentVersion
     */
    trainingGroundsEligible: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AgentVersion
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the AgentVersion interface.
 */
export function instanceOfAgentVersion(value: object): value is AgentVersion {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('agentId' in value) && !('agent_id' in value)) || (value['agentId'] === undefined && value['agent_id'] === undefined)) return false;
    if ((!('versionLabel' in value) && !('version_label' in value)) || (value['versionLabel'] === undefined && value['version_label'] === undefined)) return false;
    if ((!('competitionEligible' in value) && !('competition_eligible' in value)) || (value['competitionEligible'] === undefined && value['competition_eligible'] === undefined)) return false;
    if ((!('trainingGroundsEligible' in value) && !('training_grounds_eligible' in value)) || (value['trainingGroundsEligible'] === undefined && value['training_grounds_eligible'] === undefined)) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    return true;
}

export function AgentVersionFromJSON(json: any): AgentVersion {
    return AgentVersionFromJSONTyped(json, false);
}

export function AgentVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'agentId': json['agent_id'],
        'versionLabel': json['version_label'],
        'competitionEligible': json['competition_eligible'],
        'trainingGroundsEligible': json['training_grounds_eligible'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function AgentVersionToJSON(json: any): AgentVersion {
    return AgentVersionToJSONTyped(json, false);
}

export function AgentVersionToJSONTyped(value?: AgentVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'agent_id': value['agentId'],
        'version_label': value['versionLabel'],
        'competition_eligible': value['competitionEligible'],
        'training_grounds_eligible': value['trainingGroundsEligible'],
        'created_at': value['createdAt'].toISOString(),
    };
}

