/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Agent } from './Agent.js';
import {
    AgentFromJSON,
    AgentFromJSONTyped,
    AgentToJSON,
    AgentToJSONTyped,
} from './Agent.js';

/**
 * 
 * @export
 * @interface AgentList
 */
export interface AgentList {
    /**
     * 
     * @type {Array<Agent>}
     * @memberof AgentList
     */
    items: Array<Agent>;
    /**
     * 
     * @type {string}
     * @memberof AgentList
     */
    nextPageToken: string;
}

/**
 * Check if a given object implements the AgentList interface.
 */
export function instanceOfAgentList(value: object): value is AgentList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if ((!('nextPageToken' in value) && !('next_page_token' in value)) || (value['nextPageToken'] === undefined && value['next_page_token'] === undefined)) return false;
    return true;
}

export function AgentListFromJSON(json: any): AgentList {
    return AgentListFromJSONTyped(json, false);
}

export function AgentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AgentFromJSON)),
        'nextPageToken': json['next_page_token'],
    };
}

export function AgentListToJSON(json: any): AgentList {
    return AgentListToJSONTyped(json, false);
}

export function AgentListToJSONTyped(value?: AgentList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(AgentToJSON)),
        'next_page_token': value['nextPageToken'],
    };
}

