/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AgentVersionKeyRotated
 */
export interface AgentVersionKeyRotated {
    /**
     * 
     * @type {string}
     * @memberof AgentVersionKeyRotated
     */
    agentVersionId: string;
    /**
     * Raw new MCP auth key. Shown once.
     * @type {string}
     * @memberof AgentVersionKeyRotated
     */
    apiKey: string;
}

/**
 * Check if a given object implements the AgentVersionKeyRotated interface.
 */
export function instanceOfAgentVersionKeyRotated(value: object): value is AgentVersionKeyRotated {
    if ((!('agentVersionId' in value) && !('agent_version_id' in value)) || (value['agentVersionId'] === undefined && value['agent_version_id'] === undefined)) return false;
    if ((!('apiKey' in value) && !('api_key' in value)) || (value['apiKey'] === undefined && value['api_key'] === undefined)) return false;
    return true;
}

export function AgentVersionKeyRotatedFromJSON(json: any): AgentVersionKeyRotated {
    return AgentVersionKeyRotatedFromJSONTyped(json, false);
}

export function AgentVersionKeyRotatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentVersionKeyRotated {
    if (json == null) {
        return json;
    }
    return {
        
        'agentVersionId': json['agent_version_id'],
        'apiKey': json['api_key'],
    };
}

export function AgentVersionKeyRotatedToJSON(json: any): AgentVersionKeyRotated {
    return AgentVersionKeyRotatedToJSONTyped(json, false);
}

export function AgentVersionKeyRotatedToJSONTyped(value?: AgentVersionKeyRotated | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agent_version_id': value['agentVersionId'],
        'api_key': value['apiKey'],
    };
}

