/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Counts only status = 'completed' matches, so wins + losses + ties always equals matches.
 * 
 * @export
 * @interface AgentVersionMatchTally
 */
export interface AgentVersionMatchTally {
    /**
     * 
     * @type {number}
     * @memberof AgentVersionMatchTally
     */
    matches: number;
    /**
     * 
     * @type {number}
     * @memberof AgentVersionMatchTally
     */
    wins: number;
    /**
     * 
     * @type {number}
     * @memberof AgentVersionMatchTally
     */
    losses: number;
    /**
     * 
     * @type {number}
     * @memberof AgentVersionMatchTally
     */
    ties: number;
}

/**
 * Check if a given object implements the AgentVersionMatchTally interface.
 */
export function instanceOfAgentVersionMatchTally(value: object): value is AgentVersionMatchTally {
    if (!('matches' in value) || value['matches'] === undefined) return false;
    if (!('wins' in value) || value['wins'] === undefined) return false;
    if (!('losses' in value) || value['losses'] === undefined) return false;
    if (!('ties' in value) || value['ties'] === undefined) return false;
    return true;
}

export function AgentVersionMatchTallyFromJSON(json: any): AgentVersionMatchTally {
    return AgentVersionMatchTallyFromJSONTyped(json, false);
}

export function AgentVersionMatchTallyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentVersionMatchTally {
    if (json == null) {
        return json;
    }
    return {
        
        'matches': json['matches'],
        'wins': json['wins'],
        'losses': json['losses'],
        'ties': json['ties'],
    };
}

export function AgentVersionMatchTallyToJSON(json: any): AgentVersionMatchTally {
    return AgentVersionMatchTallyToJSONTyped(json, false);
}

export function AgentVersionMatchTallyToJSONTyped(value?: AgentVersionMatchTally | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'matches': value['matches'],
        'wins': value['wins'],
        'losses': value['losses'],
        'ties': value['ties'],
    };
}

