/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AgentVersionMatchTally } from './AgentVersionMatchTally.js';
import {
    AgentVersionMatchTallyFromJSON,
    AgentVersionMatchTallyFromJSONTyped,
    AgentVersionMatchTallyToJSON,
    AgentVersionMatchTallyToJSONTyped,
} from './AgentVersionMatchTally.js';

/**
 * 
 * @export
 * @interface AgentVersionStats
 */
export interface AgentVersionStats {
    /**
     * 
     * @type {AgentVersionMatchTally}
     * @memberof AgentVersionStats
     */
    training: AgentVersionMatchTally;
    /**
     * 
     * @type {AgentVersionMatchTally}
     * @memberof AgentVersionStats
     */
    competition: AgentVersionMatchTally;
}

/**
 * Check if a given object implements the AgentVersionStats interface.
 */
export function instanceOfAgentVersionStats(value: object): value is AgentVersionStats {
    if (!('training' in value) || value['training'] === undefined) return false;
    if (!('competition' in value) || value['competition'] === undefined) return false;
    return true;
}

export function AgentVersionStatsFromJSON(json: any): AgentVersionStats {
    return AgentVersionStatsFromJSONTyped(json, false);
}

export function AgentVersionStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentVersionStats {
    if (json == null) {
        return json;
    }
    return {
        
        'training': AgentVersionMatchTallyFromJSON(json['training']),
        'competition': AgentVersionMatchTallyFromJSON(json['competition']),
    };
}

export function AgentVersionStatsToJSON(json: any): AgentVersionStats {
    return AgentVersionStatsToJSONTyped(json, false);
}

export function AgentVersionStatsToJSONTyped(value?: AgentVersionStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'training': AgentVersionMatchTallyToJSON(value['training']),
        'competition': AgentVersionMatchTallyToJSON(value['competition']),
    };
}

