/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AgentVersionReachability
 */
export interface AgentVersionReachability {
    /**
     * Consecutive failed matchmaking probes. Resets to 0 on a successful probe, or when competition_eligible transitions from false to true via UpdateAgentVersionRequest. 3 consecutive failures auto-retires the version (competition_eligible set to false, unreachable_retired_at set).
     * 
     * @type {number}
     * @memberof AgentVersionReachability
     */
    consecutiveProbeFailures: number;
    /**
     * 
     * @type {Date}
     * @memberof AgentVersionReachability
     */
    lastProbeAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AgentVersionReachability
     */
    lastReachableAt?: Date | null;
    /**
     * When matchmaking auto-retired this version after 3 consecutive unreachable probes. Cleared when competition_eligible transitions from false to true.
     * 
     * @type {Date}
     * @memberof AgentVersionReachability
     */
    unreachableRetiredAt?: Date | null;
}

/**
 * Check if a given object implements the AgentVersionReachability interface.
 */
export function instanceOfAgentVersionReachability(value: object): value is AgentVersionReachability {
    if ((!('consecutiveProbeFailures' in (value as Record<string, any>)) && !('consecutive_probe_failures' in (value as Record<string, any>))) || ((value as Record<string, any>)['consecutiveProbeFailures'] === undefined && (value as Record<string, any>)['consecutive_probe_failures'] === undefined)) return false;
    return true;
}

export function AgentVersionReachabilityFromJSON(json: any): AgentVersionReachability {
    return AgentVersionReachabilityFromJSONTyped(json, false);
}

export function AgentVersionReachabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentVersionReachability {
    if (json == null) {
        return json;
    }
    return {
        
        'consecutiveProbeFailures': json['consecutive_probe_failures'],
        'lastProbeAt': json['last_probe_at'] === undefined ? undefined : json['last_probe_at'] === null ? null : (new Date(json['last_probe_at'])),
        'lastReachableAt': json['last_reachable_at'] === undefined ? undefined : json['last_reachable_at'] === null ? null : (new Date(json['last_reachable_at'])),
        'unreachableRetiredAt': json['unreachable_retired_at'] === undefined ? undefined : json['unreachable_retired_at'] === null ? null : (new Date(json['unreachable_retired_at'])),
    };
}

export function AgentVersionReachabilityToJSON(json: any): AgentVersionReachability {
    return AgentVersionReachabilityToJSONTyped(json, false);
}

export function AgentVersionReachabilityToJSONTyped(value?: AgentVersionReachability | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'consecutive_probe_failures': value['consecutiveProbeFailures'],
        'last_probe_at': value['lastProbeAt'] == null ? value['lastProbeAt'] : value['lastProbeAt'].toISOString(),
        'last_reachable_at': value['lastReachableAt'] == null ? value['lastReachableAt'] : value['lastReachableAt'].toISOString(),
        'unreachable_retired_at': value['unreachableRetiredAt'] == null ? value['unreachableRetiredAt'] : value['unreachableRetiredAt'].toISOString(),
    };
}

