/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AgentVersion } from './AgentVersion.js';
import {
    AgentVersionFromJSON,
    AgentVersionFromJSONTyped,
    AgentVersionToJSON,
    AgentVersionToJSONTyped,
} from './AgentVersion.js';

/**
 * 
 * @export
 * @interface AgentVersionList
 */
export interface AgentVersionList {
    /**
     * 
     * @type {Array<AgentVersion>}
     * @memberof AgentVersionList
     */
    items: Array<AgentVersion>;
}

/**
 * Check if a given object implements the AgentVersionList interface.
 */
export function instanceOfAgentVersionList(value: object): value is AgentVersionList {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function AgentVersionListFromJSON(json: any): AgentVersionList {
    return AgentVersionListFromJSONTyped(json, false);
}

export function AgentVersionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentVersionList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AgentVersionFromJSON)),
    };
}

export function AgentVersionListToJSON(json: any): AgentVersionList {
    return AgentVersionListToJSONTyped(json, false);
}

export function AgentVersionListToJSONTyped(value?: AgentVersionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(AgentVersionToJSON)),
    };
}

