/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CompetitiveOrgEntry } from './CompetitiveOrgEntry.js';
import {
    CompetitiveOrgEntryFromJSON,
    CompetitiveOrgEntryFromJSONTyped,
    CompetitiveOrgEntryToJSON,
    CompetitiveOrgEntryToJSONTyped,
} from './CompetitiveOrgEntry.js';

/**
 * 
 * @export
 * @interface CompetitiveOrgPage
 */
export interface CompetitiveOrgPage {
    /**
     * 
     * @type {Array<CompetitiveOrgEntry>}
     * @memberof CompetitiveOrgPage
     */
    items: Array<CompetitiveOrgEntry>;
    /**
     * 
     * @type {string}
     * @memberof CompetitiveOrgPage
     */
    nextPageToken: string;
}

/**
 * Check if a given object implements the CompetitiveOrgPage interface.
 */
export function instanceOfCompetitiveOrgPage(value: object): value is CompetitiveOrgPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if ((!('nextPageToken' in (value as Record<string, any>)) && !('next_page_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextPageToken'] === undefined && (value as Record<string, any>)['next_page_token'] === undefined)) return false;
    return true;
}

export function CompetitiveOrgPageFromJSON(json: any): CompetitiveOrgPage {
    return CompetitiveOrgPageFromJSONTyped(json, false);
}

export function CompetitiveOrgPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompetitiveOrgPage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(CompetitiveOrgEntryFromJSON)),
        'nextPageToken': json['next_page_token'],
    };
}

export function CompetitiveOrgPageToJSON(json: any): CompetitiveOrgPage {
    return CompetitiveOrgPageToJSONTyped(json, false);
}

export function CompetitiveOrgPageToJSONTyped(value?: CompetitiveOrgPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(CompetitiveOrgEntryToJSON)),
        'next_page_token': value['nextPageToken'],
    };
}

