/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CompetitiveOrgEntry
 */
export interface CompetitiveOrgEntry {
    /**
     * 
     * @type {number}
     * @memberof CompetitiveOrgEntry
     */
    rank: number;
    /**
     * 
     * @type {string}
     * @memberof CompetitiveOrgEntry
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitiveOrgEntry
     */
    orgName: string;
    /**
     * Count of this org's non-provisional (actually-competed) agent-versions.
     * @type {number}
     * @memberof CompetitiveOrgEntry
     */
    ratedAgentCount: number;
    /**
     * Mean Glicko-2 rating of the org's top-3 non-provisional agent-versions.
     * @type {number}
     * @memberof CompetitiveOrgEntry
     */
    score: number;
}

/**
 * Check if a given object implements the CompetitiveOrgEntry interface.
 */
export function instanceOfCompetitiveOrgEntry(value: object): value is CompetitiveOrgEntry {
    if (!('rank' in value) || value['rank'] === undefined) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    if ((!('orgName' in (value as Record<string, any>)) && !('org_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgName'] === undefined && (value as Record<string, any>)['org_name'] === undefined)) return false;
    if ((!('ratedAgentCount' in (value as Record<string, any>)) && !('rated_agent_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['ratedAgentCount'] === undefined && (value as Record<string, any>)['rated_agent_count'] === undefined)) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function CompetitiveOrgEntryFromJSON(json: any): CompetitiveOrgEntry {
    return CompetitiveOrgEntryFromJSONTyped(json, false);
}

export function CompetitiveOrgEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompetitiveOrgEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'rank': json['rank'],
        'orgId': json['org_id'],
        'orgName': json['org_name'],
        'ratedAgentCount': json['rated_agent_count'],
        'score': json['score'],
    };
}

export function CompetitiveOrgEntryToJSON(json: any): CompetitiveOrgEntry {
    return CompetitiveOrgEntryToJSONTyped(json, false);
}

export function CompetitiveOrgEntryToJSONTyped(value?: CompetitiveOrgEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rank': value['rank'],
        'org_id': value['orgId'],
        'org_name': value['orgName'],
        'rated_agent_count': value['ratedAgentCount'],
        'score': value['score'],
    };
}

