/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateTeamRequest
 */
export interface CreateTeamRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTeamRequest
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTeamRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTeamRequest
     */
    logoUrl?: string;
}

/**
 * Check if a given object implements the CreateTeamRequest interface.
 */
export function instanceOfCreateTeamRequest(value: object): value is CreateTeamRequest {
    if ((!('orgId' in value) && !('org_id' in value)) || (value['orgId'] === undefined && value['org_id'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateTeamRequestFromJSON(json: any): CreateTeamRequest {
    return CreateTeamRequestFromJSONTyped(json, false);
}

export function CreateTeamRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTeamRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orgId': json['org_id'],
        'name': json['name'],
        'logoUrl': json['logo_url'] == null ? undefined : json['logo_url'],
    };
}

export function CreateTeamRequestToJSON(json: any): CreateTeamRequest {
    return CreateTeamRequestToJSONTyped(json, false);
}

export function CreateTeamRequestToJSONTyped(value?: CreateTeamRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'org_id': value['orgId'],
        'name': value['name'],
        'logo_url': value['logoUrl'],
    };
}

