/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateAgentVersionRequest
 */
export interface CreateAgentVersionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateAgentVersionRequest
     */
    versionLabel: string;
}

/**
 * Check if a given object implements the CreateAgentVersionRequest interface.
 */
export function instanceOfCreateAgentVersionRequest(value: object): value is CreateAgentVersionRequest {
    if ((!('versionLabel' in value) && !('version_label' in value)) || (value['versionLabel'] === undefined && value['version_label'] === undefined)) return false;
    return true;
}

export function CreateAgentVersionRequestFromJSON(json: any): CreateAgentVersionRequest {
    return CreateAgentVersionRequestFromJSONTyped(json, false);
}

export function CreateAgentVersionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAgentVersionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'versionLabel': json['version_label'],
    };
}

export function CreateAgentVersionRequestToJSON(json: any): CreateAgentVersionRequest {
    return CreateAgentVersionRequestToJSONTyped(json, false);
}

export function CreateAgentVersionRequestToJSONTyped(value?: CreateAgentVersionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version_label': value['versionLabel'],
    };
}

