/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateTokenRequest
 */
export interface CreateTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTokenRequest
     */
    teamId: string;
}

/**
 * Check if a given object implements the CreateTokenRequest interface.
 */
export function instanceOfCreateTokenRequest(value: object): value is CreateTokenRequest {
    if ((!('teamId' in (value as Record<string, any>)) && !('team_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['teamId'] === undefined && (value as Record<string, any>)['team_id'] === undefined)) return false;
    return true;
}

export function CreateTokenRequestFromJSON(json: any): CreateTokenRequest {
    return CreateTokenRequestFromJSONTyped(json, false);
}

export function CreateTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'teamId': json['team_id'],
    };
}

export function CreateTokenRequestToJSON(json: any): CreateTokenRequest {
    return CreateTokenRequestToJSONTyped(json, false);
}

export function CreateTokenRequestToJSONTyped(value?: CreateTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'team_id': value['teamId'],
    };
}

