/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Dispute } from './Dispute.js';
import {
    DisputeFromJSON,
    DisputeFromJSONTyped,
    DisputeToJSON,
    DisputeToJSONTyped,
} from './Dispute.js';

/**
 * 
 * @export
 * @interface DisputeList
 */
export interface DisputeList {
    /**
     * 
     * @type {Array<Dispute>}
     * @memberof DisputeList
     */
    items: Array<Dispute>;
    /**
     * 
     * @type {string}
     * @memberof DisputeList
     */
    nextPageToken: string;
}

/**
 * Check if a given object implements the DisputeList interface.
 */
export function instanceOfDisputeList(value: object): value is DisputeList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if ((!('nextPageToken' in (value as Record<string, any>)) && !('next_page_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextPageToken'] === undefined && (value as Record<string, any>)['next_page_token'] === undefined)) return false;
    return true;
}

export function DisputeListFromJSON(json: any): DisputeList {
    return DisputeListFromJSONTyped(json, false);
}

export function DisputeListFromJSONTyped(json: any, ignoreDiscriminator: boolean): DisputeList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(DisputeFromJSON)),
        'nextPageToken': json['next_page_token'],
    };
}

export function DisputeListToJSON(json: any): DisputeList {
    return DisputeListToJSONTyped(json, false);
}

export function DisputeListToJSONTyped(value?: DisputeList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(DisputeToJSON)),
        'next_page_token': value['nextPageToken'],
    };
}

