/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Dispute
 */
export interface Dispute {
    /**
     * 
     * @type {string}
     * @memberof Dispute
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Dispute
     */
    matchId: string;
    /**
     * 
     * @type {string}
     * @memberof Dispute
     */
    filedByTeamId: string;
    /**
     * 
     * @type {string}
     * @memberof Dispute
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof Dispute
     */
    reason: string;
    /**
     * 
     * @type {number}
     * @memberof Dispute
     */
    impulse?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof Dispute
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Dispute interface.
 */
export function instanceOfDispute(value: object): value is Dispute {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('matchId' in value) && !('match_id' in value)) || (value['matchId'] === undefined && value['match_id'] === undefined)) return false;
    if ((!('filedByTeamId' in value) && !('filed_by_team_id' in value)) || (value['filedByTeamId'] === undefined && value['filed_by_team_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    return true;
}

export function DisputeFromJSON(json: any): Dispute {
    return DisputeFromJSONTyped(json, false);
}

export function DisputeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Dispute {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'matchId': json['match_id'],
        'filedByTeamId': json['filed_by_team_id'],
        'status': json['status'],
        'reason': json['reason'],
        'impulse': json['impulse'] == null ? undefined : json['impulse'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function DisputeToJSON(json: any): Dispute {
    return DisputeToJSONTyped(json, false);
}

export function DisputeToJSONTyped(value?: Dispute | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'match_id': value['matchId'],
        'filed_by_team_id': value['filedByTeamId'],
        'status': value['status'],
        'reason': value['reason'],
        'impulse': value['impulse'],
        'created_at': value['createdAt'].toISOString(),
    };
}

