/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface FileDisputeRequest
 */
export interface FileDisputeRequest {
    /**
     * 
     * @type {string}
     * @memberof FileDisputeRequest
     */
    reason: string;
    /**
     * Optional impulse number this filing contests, per game-and-protocol.md#command-log--replay-format.
     * 
     * @type {number}
     * @memberof FileDisputeRequest
     */
    impulse?: number;
}

/**
 * Check if a given object implements the FileDisputeRequest interface.
 */
export function instanceOfFileDisputeRequest(value: object): value is FileDisputeRequest {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function FileDisputeRequestFromJSON(json: any): FileDisputeRequest {
    return FileDisputeRequestFromJSONTyped(json, false);
}

export function FileDisputeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileDisputeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'],
        'impulse': json['impulse'] == null ? undefined : json['impulse'],
    };
}

export function FileDisputeRequestToJSON(json: any): FileDisputeRequest {
    return FileDisputeRequestToJSONTyped(json, false);
}

export function FileDisputeRequestToJSONTyped(value?: FileDisputeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
        'impulse': value['impulse'],
    };
}

