/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { HistoricLeaderboardEntry } from './HistoricLeaderboardEntry.js';
import {
    HistoricLeaderboardEntryFromJSON,
    HistoricLeaderboardEntryFromJSONTyped,
    HistoricLeaderboardEntryToJSON,
    HistoricLeaderboardEntryToJSONTyped,
} from './HistoricLeaderboardEntry.js';

/**
 * 
 * @export
 * @interface HistoricLeaderboardPage
 */
export interface HistoricLeaderboardPage {
    /**
     * 
     * @type {Array<HistoricLeaderboardEntry>}
     * @memberof HistoricLeaderboardPage
     */
    items: Array<HistoricLeaderboardEntry>;
    /**
     * 
     * @type {string}
     * @memberof HistoricLeaderboardPage
     */
    nextPageToken: string;
}

/**
 * Check if a given object implements the HistoricLeaderboardPage interface.
 */
export function instanceOfHistoricLeaderboardPage(value: object): value is HistoricLeaderboardPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if ((!('nextPageToken' in (value as Record<string, any>)) && !('next_page_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextPageToken'] === undefined && (value as Record<string, any>)['next_page_token'] === undefined)) return false;
    return true;
}

export function HistoricLeaderboardPageFromJSON(json: any): HistoricLeaderboardPage {
    return HistoricLeaderboardPageFromJSONTyped(json, false);
}

export function HistoricLeaderboardPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoricLeaderboardPage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(HistoricLeaderboardEntryFromJSON)),
        'nextPageToken': json['next_page_token'],
    };
}

export function HistoricLeaderboardPageToJSON(json: any): HistoricLeaderboardPage {
    return HistoricLeaderboardPageToJSONTyped(json, false);
}

export function HistoricLeaderboardPageToJSONTyped(value?: HistoricLeaderboardPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(HistoricLeaderboardEntryToJSON)),
        'next_page_token': value['nextPageToken'],
    };
}

