/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface HistoricLeaderboardEntry
 */
export interface HistoricLeaderboardEntry {
    /**
     * 
     * @type {number}
     * @memberof HistoricLeaderboardEntry
     */
    rank: number;
    /**
     * 
     * @type {string}
     * @memberof HistoricLeaderboardEntry
     */
    agentVersionId: string;
    /**
     * Glicko-2 rating (r). Default for a new agent-version is 1500.
     * @type {number}
     * @memberof HistoricLeaderboardEntry
     */
    rating: number;
    /**
     * Glicko-2 rating deviation (RD). Default for a new agent-version is 350.
     * @type {number}
     * @memberof HistoricLeaderboardEntry
     */
    ratingDeviation: number;
    /**
     * True until enough official matches have narrowed RD.
     * @type {boolean}
     * @memberof HistoricLeaderboardEntry
     */
    provisional: boolean;
    /**
     * r minus 2 times RD at retirement, frozen.
     * @type {number}
     * @memberof HistoricLeaderboardEntry
     */
    conservativeRating: number;
    /**
     * Highest r ever reached while active.
     * @type {number}
     * @memberof HistoricLeaderboardEntry
     */
    peakRating: number;
    /**
     * RD at the moment peak_rating was reached.
     * @type {number}
     * @memberof HistoricLeaderboardEntry
     */
    peakRatingDeviation: number;
}

/**
 * Check if a given object implements the HistoricLeaderboardEntry interface.
 */
export function instanceOfHistoricLeaderboardEntry(value: object): value is HistoricLeaderboardEntry {
    if (!('rank' in value) || value['rank'] === undefined) return false;
    if ((!('agentVersionId' in value) && !('agent_version_id' in value)) || (value['agentVersionId'] === undefined && value['agent_version_id'] === undefined)) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if ((!('ratingDeviation' in value) && !('rating_deviation' in value)) || (value['ratingDeviation'] === undefined && value['rating_deviation'] === undefined)) return false;
    if (!('provisional' in value) || value['provisional'] === undefined) return false;
    if ((!('conservativeRating' in value) && !('conservative_rating' in value)) || (value['conservativeRating'] === undefined && value['conservative_rating'] === undefined)) return false;
    if ((!('peakRating' in value) && !('peak_rating' in value)) || (value['peakRating'] === undefined && value['peak_rating'] === undefined)) return false;
    if ((!('peakRatingDeviation' in value) && !('peak_rating_deviation' in value)) || (value['peakRatingDeviation'] === undefined && value['peak_rating_deviation'] === undefined)) return false;
    return true;
}

export function HistoricLeaderboardEntryFromJSON(json: any): HistoricLeaderboardEntry {
    return HistoricLeaderboardEntryFromJSONTyped(json, false);
}

export function HistoricLeaderboardEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoricLeaderboardEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'rank': json['rank'],
        'agentVersionId': json['agent_version_id'],
        'rating': json['rating'],
        'ratingDeviation': json['rating_deviation'],
        'provisional': json['provisional'],
        'conservativeRating': json['conservative_rating'],
        'peakRating': json['peak_rating'],
        'peakRatingDeviation': json['peak_rating_deviation'],
    };
}

export function HistoricLeaderboardEntryToJSON(json: any): HistoricLeaderboardEntry {
    return HistoricLeaderboardEntryToJSONTyped(json, false);
}

export function HistoricLeaderboardEntryToJSONTyped(value?: HistoricLeaderboardEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rank': value['rank'],
        'agent_version_id': value['agentVersionId'],
        'rating': value['rating'],
        'rating_deviation': value['ratingDeviation'],
        'provisional': value['provisional'],
        'conservative_rating': value['conservativeRating'],
        'peak_rating': value['peakRating'],
        'peak_rating_deviation': value['peakRatingDeviation'],
    };
}

