/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface LaunchMatchRequest
 */
export interface LaunchMatchRequest {
    /**
     * 
     * @type {string}
     * @memberof LaunchMatchRequest
     */
    challengerAgentVersionId: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchMatchRequest
     */
    opponentAgentVersionId: string;
    /**
     * Not yet supported — omit this field. Reserved for a future scenario registry.
     * 
     * @type {string}
     * @memberof LaunchMatchRequest
     */
    scenarioId?: string;
}

/**
 * Check if a given object implements the LaunchMatchRequest interface.
 */
export function instanceOfLaunchMatchRequest(value: object): value is LaunchMatchRequest {
    if ((!('challengerAgentVersionId' in (value as Record<string, any>)) && !('challenger_agent_version_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['challengerAgentVersionId'] === undefined && (value as Record<string, any>)['challenger_agent_version_id'] === undefined)) return false;
    if ((!('opponentAgentVersionId' in (value as Record<string, any>)) && !('opponent_agent_version_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['opponentAgentVersionId'] === undefined && (value as Record<string, any>)['opponent_agent_version_id'] === undefined)) return false;
    return true;
}

export function LaunchMatchRequestFromJSON(json: any): LaunchMatchRequest {
    return LaunchMatchRequestFromJSONTyped(json, false);
}

export function LaunchMatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaunchMatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'challengerAgentVersionId': json['challenger_agent_version_id'],
        'opponentAgentVersionId': json['opponent_agent_version_id'],
        'scenarioId': json['scenario_id'] == null ? undefined : json['scenario_id'],
    };
}

export function LaunchMatchRequestToJSON(json: any): LaunchMatchRequest {
    return LaunchMatchRequestToJSONTyped(json, false);
}

export function LaunchMatchRequestToJSONTyped(value?: LaunchMatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'challenger_agent_version_id': value['challengerAgentVersionId'],
        'opponent_agent_version_id': value['opponentAgentVersionId'],
        'scenario_id': value['scenarioId'],
    };
}

