/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface LeaderboardEntry
 */
export interface LeaderboardEntry {
    /**
     * 
     * @type {number}
     * @memberof LeaderboardEntry
     */
    rank: number;
    /**
     * 
     * @type {string}
     * @memberof LeaderboardEntry
     */
    agentVersionId: string;
    /**
     * Glicko-2 rating (r). Default for a new agent-version is 1500.
     * @type {number}
     * @memberof LeaderboardEntry
     */
    rating: number;
    /**
     * Glicko-2 rating deviation (RD). Default for a new agent-version is 350.
     * @type {number}
     * @memberof LeaderboardEntry
     */
    ratingDeviation: number;
    /**
     * True until enough official matches have narrowed RD.
     * @type {boolean}
     * @memberof LeaderboardEntry
     */
    provisional: boolean;
}

/**
 * Check if a given object implements the LeaderboardEntry interface.
 */
export function instanceOfLeaderboardEntry(value: object): value is LeaderboardEntry {
    if (!('rank' in value) || value['rank'] === undefined) return false;
    if ((!('agentVersionId' in value) && !('agent_version_id' in value)) || (value['agentVersionId'] === undefined && value['agent_version_id'] === undefined)) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if ((!('ratingDeviation' in value) && !('rating_deviation' in value)) || (value['ratingDeviation'] === undefined && value['rating_deviation'] === undefined)) return false;
    if (!('provisional' in value) || value['provisional'] === undefined) return false;
    return true;
}

export function LeaderboardEntryFromJSON(json: any): LeaderboardEntry {
    return LeaderboardEntryFromJSONTyped(json, false);
}

export function LeaderboardEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'rank': json['rank'],
        'agentVersionId': json['agent_version_id'],
        'rating': json['rating'],
        'ratingDeviation': json['rating_deviation'],
        'provisional': json['provisional'],
    };
}

export function LeaderboardEntryToJSON(json: any): LeaderboardEntry {
    return LeaderboardEntryToJSONTyped(json, false);
}

export function LeaderboardEntryToJSONTyped(value?: LeaderboardEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rank': value['rank'],
        'agent_version_id': value['agentVersionId'],
        'rating': value['rating'],
        'rating_deviation': value['ratingDeviation'],
        'provisional': value['provisional'],
    };
}

