/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { LeaderboardEntry } from './LeaderboardEntry.js';
import {
    LeaderboardEntryFromJSON,
    LeaderboardEntryFromJSONTyped,
    LeaderboardEntryToJSON,
    LeaderboardEntryToJSONTyped,
} from './LeaderboardEntry.js';

/**
 * 
 * @export
 * @interface LeaderboardPage
 */
export interface LeaderboardPage {
    /**
     * 
     * @type {Array<LeaderboardEntry>}
     * @memberof LeaderboardPage
     */
    items: Array<LeaderboardEntry>;
    /**
     * 
     * @type {string}
     * @memberof LeaderboardPage
     */
    nextPageToken: string;
}

/**
 * Check if a given object implements the LeaderboardPage interface.
 */
export function instanceOfLeaderboardPage(value: object): value is LeaderboardPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if ((!('nextPageToken' in value) && !('next_page_token' in value)) || (value['nextPageToken'] === undefined && value['next_page_token'] === undefined)) return false;
    return true;
}

export function LeaderboardPageFromJSON(json: any): LeaderboardPage {
    return LeaderboardPageFromJSONTyped(json, false);
}

export function LeaderboardPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardPage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(LeaderboardEntryFromJSON)),
        'nextPageToken': json['next_page_token'],
    };
}

export function LeaderboardPageToJSON(json: any): LeaderboardPage {
    return LeaderboardPageToJSONTyped(json, false);
}

export function LeaderboardPageToJSONTyped(value?: LeaderboardPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(LeaderboardEntryToJSON)),
        'next_page_token': value['nextPageToken'],
    };
}

