/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface LeaderboardEntry
 */
export interface LeaderboardEntry {
    /**
     * 
     * @type {number}
     * @memberof LeaderboardEntry
     */
    rank: number;
    /**
     * 
     * @type {string}
     * @memberof LeaderboardEntry
     */
    agentVersionId: string;
    /**
     * 
     * @type {string}
     * @memberof LeaderboardEntry
     */
    agentName: string;
    /**
     * 
     * @type {string}
     * @memberof LeaderboardEntry
     */
    agentVersionLabel: string;
    /**
     * 
     * @type {string}
     * @memberof LeaderboardEntry
     */
    teamName: string;
    /**
     * 
     * @type {string}
     * @memberof LeaderboardEntry
     */
    orgName: string;
    /**
     * Glicko-2 rating (r). Default for a new agent-version is 1500.
     * @type {number}
     * @memberof LeaderboardEntry
     */
    rating: number;
    /**
     * Glicko-2 rating deviation (RD). Default for a new agent-version is 350.
     * @type {number}
     * @memberof LeaderboardEntry
     */
    ratingDeviation: number;
    /**
     * True until enough official matches have narrowed RD.
     * @type {boolean}
     * @memberof LeaderboardEntry
     */
    provisional: boolean;
}

/**
 * Check if a given object implements the LeaderboardEntry interface.
 */
export function instanceOfLeaderboardEntry(value: object): value is LeaderboardEntry {
    if (!('rank' in value) || value['rank'] === undefined) return false;
    if ((!('agentVersionId' in (value as Record<string, any>)) && !('agent_version_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['agentVersionId'] === undefined && (value as Record<string, any>)['agent_version_id'] === undefined)) return false;
    if ((!('agentName' in (value as Record<string, any>)) && !('agent_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['agentName'] === undefined && (value as Record<string, any>)['agent_name'] === undefined)) return false;
    if ((!('agentVersionLabel' in (value as Record<string, any>)) && !('agent_version_label' in (value as Record<string, any>))) || ((value as Record<string, any>)['agentVersionLabel'] === undefined && (value as Record<string, any>)['agent_version_label'] === undefined)) return false;
    if ((!('teamName' in (value as Record<string, any>)) && !('team_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['teamName'] === undefined && (value as Record<string, any>)['team_name'] === undefined)) return false;
    if ((!('orgName' in (value as Record<string, any>)) && !('org_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgName'] === undefined && (value as Record<string, any>)['org_name'] === undefined)) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if ((!('ratingDeviation' in (value as Record<string, any>)) && !('rating_deviation' in (value as Record<string, any>))) || ((value as Record<string, any>)['ratingDeviation'] === undefined && (value as Record<string, any>)['rating_deviation'] === undefined)) return false;
    if (!('provisional' in value) || value['provisional'] === undefined) return false;
    return true;
}

export function LeaderboardEntryFromJSON(json: any): LeaderboardEntry {
    return LeaderboardEntryFromJSONTyped(json, false);
}

export function LeaderboardEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'rank': json['rank'],
        'agentVersionId': json['agent_version_id'],
        'agentName': json['agent_name'],
        'agentVersionLabel': json['agent_version_label'],
        'teamName': json['team_name'],
        'orgName': json['org_name'],
        'rating': json['rating'],
        'ratingDeviation': json['rating_deviation'],
        'provisional': json['provisional'],
    };
}

export function LeaderboardEntryToJSON(json: any): LeaderboardEntry {
    return LeaderboardEntryToJSONTyped(json, false);
}

export function LeaderboardEntryToJSONTyped(value?: LeaderboardEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rank': value['rank'],
        'agent_version_id': value['agentVersionId'],
        'agent_name': value['agentName'],
        'agent_version_label': value['agentVersionLabel'],
        'team_name': value['teamName'],
        'org_name': value['orgName'],
        'rating': value['rating'],
        'rating_deviation': value['ratingDeviation'],
        'provisional': value['provisional'],
    };
}

