/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Match } from './Match.js';
import {
    MatchFromJSON,
    MatchFromJSONTyped,
    MatchToJSON,
    MatchToJSONTyped,
} from './Match.js';

/**
 * 
 * @export
 * @interface MatchList
 */
export interface MatchList {
    /**
     * 
     * @type {Array<Match>}
     * @memberof MatchList
     */
    items: Array<Match>;
    /**
     * 
     * @type {string}
     * @memberof MatchList
     */
    nextPageToken: string;
}

/**
 * Check if a given object implements the MatchList interface.
 */
export function instanceOfMatchList(value: object): value is MatchList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if ((!('nextPageToken' in value) && !('next_page_token' in value)) || (value['nextPageToken'] === undefined && value['next_page_token'] === undefined)) return false;
    return true;
}

export function MatchListFromJSON(json: any): MatchList {
    return MatchListFromJSONTyped(json, false);
}

export function MatchListFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(MatchFromJSON)),
        'nextPageToken': json['next_page_token'],
    };
}

export function MatchListToJSON(json: any): MatchList {
    return MatchListToJSONTyped(json, false);
}

export function MatchListToJSONTyped(value?: MatchList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(MatchToJSON)),
        'next_page_token': value['nextPageToken'],
    };
}

