/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Match
 */
export interface Match {
    /**
     * 
     * @type {string}
     * @memberof Match
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Match
     */
    agentVersionA: string;
    /**
     * 
     * @type {string}
     * @memberof Match
     */
    agentVersionB: string;
    /**
     * 
     * @type {string}
     * @memberof Match
     */
    matchType: string;
    /**
     * 
     * @type {string}
     * @memberof Match
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof Match
     */
    winnerAgentVersionId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Match
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Match interface.
 */
export function instanceOfMatch(value: object): value is Match {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('agentVersionA' in value) && !('agent_version_a' in value)) || (value['agentVersionA'] === undefined && value['agent_version_a'] === undefined)) return false;
    if ((!('agentVersionB' in value) && !('agent_version_b' in value)) || (value['agentVersionB'] === undefined && value['agent_version_b'] === undefined)) return false;
    if ((!('matchType' in value) && !('match_type' in value)) || (value['matchType'] === undefined && value['match_type'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    return true;
}

export function MatchFromJSON(json: any): Match {
    return MatchFromJSONTyped(json, false);
}

export function MatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): Match {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'agentVersionA': json['agent_version_a'],
        'agentVersionB': json['agent_version_b'],
        'matchType': json['match_type'],
        'status': json['status'],
        'winnerAgentVersionId': json['winner_agent_version_id'] == null ? undefined : json['winner_agent_version_id'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function MatchToJSON(json: any): Match {
    return MatchToJSONTyped(json, false);
}

export function MatchToJSONTyped(value?: Match | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'agent_version_a': value['agentVersionA'],
        'agent_version_b': value['agentVersionB'],
        'match_type': value['matchType'],
        'status': value['status'],
        'winner_agent_version_id': value['winnerAgentVersionId'],
        'created_at': value['createdAt'].toISOString(),
    };
}

