/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MatchLaunched
 */
export interface MatchLaunched {
    /**
     * 
     * @type {string}
     * @memberof MatchLaunched
     */
    matchId: string;
    /**
     * Always "running" — launch starts the match in-process immediately.
     * @type {string}
     * @memberof MatchLaunched
     */
    status: string;
}

/**
 * Check if a given object implements the MatchLaunched interface.
 */
export function instanceOfMatchLaunched(value: object): value is MatchLaunched {
    if ((!('matchId' in (value as Record<string, any>)) && !('match_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['matchId'] === undefined && (value as Record<string, any>)['match_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function MatchLaunchedFromJSON(json: any): MatchLaunched {
    return MatchLaunchedFromJSONTyped(json, false);
}

export function MatchLaunchedFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchLaunched {
    if (json == null) {
        return json;
    }
    return {
        
        'matchId': json['match_id'],
        'status': json['status'],
    };
}

export function MatchLaunchedToJSON(json: any): MatchLaunched {
    return MatchLaunchedToJSONTyped(json, false);
}

export function MatchLaunchedToJSONTyped(value?: MatchLaunched | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'match_id': value['matchId'],
        'status': value['status'],
    };
}

