/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Organization } from './Organization.js';
import {
    OrganizationFromJSON,
    OrganizationFromJSONTyped,
    OrganizationToJSON,
    OrganizationToJSONTyped,
} from './Organization.js';

/**
 * 
 * @export
 * @interface OrganizationList
 */
export interface OrganizationList {
    /**
     * 
     * @type {Array<Organization>}
     * @memberof OrganizationList
     */
    items: Array<Organization>;
    /**
     * 
     * @type {string}
     * @memberof OrganizationList
     */
    nextPageToken: string;
}

/**
 * Check if a given object implements the OrganizationList interface.
 */
export function instanceOfOrganizationList(value: object): value is OrganizationList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if ((!('nextPageToken' in (value as Record<string, any>)) && !('next_page_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextPageToken'] === undefined && (value as Record<string, any>)['next_page_token'] === undefined)) return false;
    return true;
}

export function OrganizationListFromJSON(json: any): OrganizationList {
    return OrganizationListFromJSONTyped(json, false);
}

export function OrganizationListFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(OrganizationFromJSON)),
        'nextPageToken': json['next_page_token'],
    };
}

export function OrganizationListToJSON(json: any): OrganizationList {
    return OrganizationListToJSONTyped(json, false);
}

export function OrganizationListToJSONTyped(value?: OrganizationList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(OrganizationToJSON)),
        'next_page_token': value['nextPageToken'],
    };
}

