/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OrgMember
 */
export interface OrgMember {
    /**
     * 
     * @type {string}
     * @memberof OrgMember
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof OrgMember
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof OrgMember
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof OrgMember
     */
    displayName: string;
    /**
     * This member's role weight (member=3, admin=4, owner=5).
     * @type {number}
     * @memberof OrgMember
     */
    roleWeight: number;
}

/**
 * Check if a given object implements the OrgMember interface.
 */
export function instanceOfOrgMember(value: object): value is OrgMember {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if ((!('displayName' in (value as Record<string, any>)) && !('display_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['displayName'] === undefined && (value as Record<string, any>)['display_name'] === undefined)) return false;
    if ((!('roleWeight' in (value as Record<string, any>)) && !('role_weight' in (value as Record<string, any>))) || ((value as Record<string, any>)['roleWeight'] === undefined && (value as Record<string, any>)['role_weight'] === undefined)) return false;
    return true;
}

export function OrgMemberFromJSON(json: any): OrgMember {
    return OrgMemberFromJSONTyped(json, false);
}

export function OrgMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgMember {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'email': json['email'],
        'displayName': json['display_name'],
        'roleWeight': json['role_weight'],
    };
}

export function OrgMemberToJSON(json: any): OrgMember {
    return OrgMemberToJSONTyped(json, false);
}

export function OrgMemberToJSONTyped(value?: OrgMember | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created_at': value['createdAt'].toISOString(),
        'email': value['email'],
        'display_name': value['displayName'],
        'role_weight': value['roleWeight'],
    };
}

