/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OrgMember } from './OrgMember.js';
import {
    OrgMemberFromJSON,
    OrgMemberFromJSONTyped,
    OrgMemberToJSON,
    OrgMemberToJSONTyped,
} from './OrgMember.js';

/**
 * 
 * @export
 * @interface OrgMemberList
 */
export interface OrgMemberList {
    /**
     * 
     * @type {Array<OrgMember>}
     * @memberof OrgMemberList
     */
    items: Array<OrgMember>;
    /**
     * 
     * @type {string}
     * @memberof OrgMemberList
     */
    nextPageToken: string;
}

/**
 * Check if a given object implements the OrgMemberList interface.
 */
export function instanceOfOrgMemberList(value: object): value is OrgMemberList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if ((!('nextPageToken' in (value as Record<string, any>)) && !('next_page_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextPageToken'] === undefined && (value as Record<string, any>)['next_page_token'] === undefined)) return false;
    return true;
}

export function OrgMemberListFromJSON(json: any): OrgMemberList {
    return OrgMemberListFromJSONTyped(json, false);
}

export function OrgMemberListFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgMemberList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(OrgMemberFromJSON)),
        'nextPageToken': json['next_page_token'],
    };
}

export function OrgMemberListToJSON(json: any): OrgMemberList {
    return OrgMemberListToJSONTyped(json, false);
}

export function OrgMemberListToJSONTyped(value?: OrgMemberList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(OrgMemberToJSON)),
        'next_page_token': value['nextPageToken'],
    };
}

