/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PendingInvitation
 */
export interface PendingInvitation {
    /**
     * Clerk's own invitation ID, not an internal gzm_ id.
     * @type {string}
     * @memberof PendingInvitation
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PendingInvitation
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof PendingInvitation
     */
    email: string;
    /**
     * The invited role weight — always 3 (member) or 4 (admin).
     * @type {number}
     * @memberof PendingInvitation
     */
    roleWeight: number;
    /**
     * 
     * @type {PendingInvitationStatusEnum}
     * @memberof PendingInvitation
     */
    status: PendingInvitationStatusEnum;
    /**
     * Internal user id of the org admin/owner who sent the invite.
     * @type {string}
     * @memberof PendingInvitation
     */
    invitedBy: string;
    /**
     * 
     * @type {Date}
     * @memberof PendingInvitation
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PendingInvitation
     */
    updatedAt: Date;
}

/**
* @export
* @enum {string}
*/
export enum PendingInvitationStatusEnum {
    Pending = 'pending',
    Accepted = 'accepted',
    Revoked = 'revoked'
}


/**
 * Check if a given object implements the PendingInvitation interface.
 */
export function instanceOfPendingInvitation(value: object): value is PendingInvitation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if ((!('roleWeight' in (value as Record<string, any>)) && !('role_weight' in (value as Record<string, any>))) || ((value as Record<string, any>)['roleWeight'] === undefined && (value as Record<string, any>)['role_weight'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('invitedBy' in (value as Record<string, any>)) && !('invited_by' in (value as Record<string, any>))) || ((value as Record<string, any>)['invitedBy'] === undefined && (value as Record<string, any>)['invited_by'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function PendingInvitationFromJSON(json: any): PendingInvitation {
    return PendingInvitationFromJSONTyped(json, false);
}

export function PendingInvitationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PendingInvitation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'orgId': json['org_id'],
        'email': json['email'],
        'roleWeight': json['role_weight'],
        'status': json['status'],
        'invitedBy': json['invited_by'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function PendingInvitationToJSON(json: any): PendingInvitation {
    return PendingInvitationToJSONTyped(json, false);
}

export function PendingInvitationToJSONTyped(value?: PendingInvitation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'org_id': value['orgId'],
        'email': value['email'],
        'role_weight': value['roleWeight'],
        'status': value['status'],
        'invited_by': value['invitedBy'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

