/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PendingInvitation } from './PendingInvitation.js';
import {
    PendingInvitationFromJSON,
    PendingInvitationFromJSONTyped,
    PendingInvitationToJSON,
    PendingInvitationToJSONTyped,
} from './PendingInvitation.js';

/**
 * 
 * @export
 * @interface PendingInvitationList
 */
export interface PendingInvitationList {
    /**
     * 
     * @type {Array<PendingInvitation>}
     * @memberof PendingInvitationList
     */
    items: Array<PendingInvitation>;
    /**
     * 
     * @type {string}
     * @memberof PendingInvitationList
     */
    nextPageToken: string;
}

/**
 * Check if a given object implements the PendingInvitationList interface.
 */
export function instanceOfPendingInvitationList(value: object): value is PendingInvitationList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if ((!('nextPageToken' in (value as Record<string, any>)) && !('next_page_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextPageToken'] === undefined && (value as Record<string, any>)['next_page_token'] === undefined)) return false;
    return true;
}

export function PendingInvitationListFromJSON(json: any): PendingInvitationList {
    return PendingInvitationListFromJSONTyped(json, false);
}

export function PendingInvitationListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PendingInvitationList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PendingInvitationFromJSON)),
        'nextPageToken': json['next_page_token'],
    };
}

export function PendingInvitationListToJSON(json: any): PendingInvitationList {
    return PendingInvitationListToJSONTyped(json, false);
}

export function PendingInvitationListToJSONTyped(value?: PendingInvitationList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PendingInvitationToJSON)),
        'next_page_token': value['nextPageToken'],
    };
}

