/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PersonalApiToken } from './PersonalApiToken.js';
import {
    PersonalApiTokenFromJSON,
    PersonalApiTokenFromJSONTyped,
    PersonalApiTokenToJSON,
    PersonalApiTokenToJSONTyped,
} from './PersonalApiToken.js';

/**
 * 
 * @export
 * @interface PersonalApiTokenList
 */
export interface PersonalApiTokenList {
    /**
     * 
     * @type {Array<PersonalApiToken>}
     * @memberof PersonalApiTokenList
     */
    items: Array<PersonalApiToken>;
    /**
     * 
     * @type {string}
     * @memberof PersonalApiTokenList
     */
    nextPageToken: string;
}

/**
 * Check if a given object implements the PersonalApiTokenList interface.
 */
export function instanceOfPersonalApiTokenList(value: object): value is PersonalApiTokenList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if ((!('nextPageToken' in (value as Record<string, any>)) && !('next_page_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextPageToken'] === undefined && (value as Record<string, any>)['next_page_token'] === undefined)) return false;
    return true;
}

export function PersonalApiTokenListFromJSON(json: any): PersonalApiTokenList {
    return PersonalApiTokenListFromJSONTyped(json, false);
}

export function PersonalApiTokenListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalApiTokenList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PersonalApiTokenFromJSON)),
        'nextPageToken': json['next_page_token'],
    };
}

export function PersonalApiTokenListToJSON(json: any): PersonalApiTokenList {
    return PersonalApiTokenListToJSONTyped(json, false);
}

export function PersonalApiTokenListToJSONTyped(value?: PersonalApiTokenList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PersonalApiTokenToJSON)),
        'next_page_token': value['nextPageToken'],
    };
}

