/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PersonalApiTokenCreated
 */
export interface PersonalApiTokenCreated {
    /**
     * 
     * @type {string}
     * @memberof PersonalApiTokenCreated
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalApiTokenCreated
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalApiTokenCreated
     */
    teamId: string;
    /**
     * 
     * @type {Date}
     * @memberof PersonalApiTokenCreated
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PersonalApiTokenCreated
     */
    revokedAt?: Date | null;
    /**
     * Raw token value, prefixed gismo_pat_. Shown once; never retrievable again.
     * 
     * @type {string}
     * @memberof PersonalApiTokenCreated
     */
    token: string;
}

/**
 * Check if a given object implements the PersonalApiTokenCreated interface.
 */
export function instanceOfPersonalApiTokenCreated(value: object): value is PersonalApiTokenCreated {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('userId' in (value as Record<string, any>)) && !('user_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['userId'] === undefined && (value as Record<string, any>)['user_id'] === undefined)) return false;
    if ((!('teamId' in (value as Record<string, any>)) && !('team_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['teamId'] === undefined && (value as Record<string, any>)['team_id'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function PersonalApiTokenCreatedFromJSON(json: any): PersonalApiTokenCreated {
    return PersonalApiTokenCreatedFromJSONTyped(json, false);
}

export function PersonalApiTokenCreatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalApiTokenCreated {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'teamId': json['team_id'],
        'createdAt': (new Date(json['created_at'])),
        'revokedAt': json['revoked_at'] === undefined ? undefined : json['revoked_at'] === null ? null : (new Date(json['revoked_at'])),
        'token': json['token'],
    };
}

export function PersonalApiTokenCreatedToJSON(json: any): PersonalApiTokenCreated {
    return PersonalApiTokenCreatedToJSONTyped(json, false);
}

export function PersonalApiTokenCreatedToJSONTyped(value?: PersonalApiTokenCreated | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'team_id': value['teamId'],
        'created_at': value['createdAt'].toISOString(),
        'revoked_at': value['revokedAt'] == null ? value['revokedAt'] : value['revokedAt'].toISOString(),
        'token': value['token'],
    };
}

