/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SendInvitationRequest
 */
export interface SendInvitationRequest {
    /**
     * 
     * @type {string}
     * @memberof SendInvitationRequest
     */
    email: string;
    /**
     * 3 (member) or 4 (admin) — an invitation can never mint an owner.
     * @type {SendInvitationRequestRoleWeightEnum}
     * @memberof SendInvitationRequest
     */
    roleWeight: SendInvitationRequestRoleWeightEnum;
}

/**
* @export
* @enum {string}
*/
export enum SendInvitationRequestRoleWeightEnum {
    NUMBER_3 = 3,
    NUMBER_4 = 4
}


/**
 * Check if a given object implements the SendInvitationRequest interface.
 */
export function instanceOfSendInvitationRequest(value: object): value is SendInvitationRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if ((!('roleWeight' in (value as Record<string, any>)) && !('role_weight' in (value as Record<string, any>))) || ((value as Record<string, any>)['roleWeight'] === undefined && (value as Record<string, any>)['role_weight'] === undefined)) return false;
    return true;
}

export function SendInvitationRequestFromJSON(json: any): SendInvitationRequest {
    return SendInvitationRequestFromJSONTyped(json, false);
}

export function SendInvitationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendInvitationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'roleWeight': json['role_weight'],
    };
}

export function SendInvitationRequestToJSON(json: any): SendInvitationRequest {
    return SendInvitationRequestToJSONTyped(json, false);
}

export function SendInvitationRequestToJSONTyped(value?: SendInvitationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'role_weight': value['roleWeight'],
    };
}

