/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { TeamAgentVersion } from './TeamAgentVersion.js';
import {
    TeamAgentVersionFromJSON,
    TeamAgentVersionFromJSONTyped,
    TeamAgentVersionToJSON,
    TeamAgentVersionToJSONTyped,
} from './TeamAgentVersion.js';

/**
 * 
 * @export
 * @interface TeamAgentVersionList
 */
export interface TeamAgentVersionList {
    /**
     * 
     * @type {Array<TeamAgentVersion>}
     * @memberof TeamAgentVersionList
     */
    items: Array<TeamAgentVersion>;
}

/**
 * Check if a given object implements the TeamAgentVersionList interface.
 */
export function instanceOfTeamAgentVersionList(value: object): value is TeamAgentVersionList {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function TeamAgentVersionListFromJSON(json: any): TeamAgentVersionList {
    return TeamAgentVersionListFromJSONTyped(json, false);
}

export function TeamAgentVersionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamAgentVersionList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TeamAgentVersionFromJSON)),
    };
}

export function TeamAgentVersionListToJSON(json: any): TeamAgentVersionList {
    return TeamAgentVersionListToJSONTyped(json, false);
}

export function TeamAgentVersionListToJSONTyped(value?: TeamAgentVersionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(TeamAgentVersionToJSON)),
    };
}

