/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Team } from './Team.js';
import {
    TeamFromJSON,
    TeamFromJSONTyped,
    TeamToJSON,
    TeamToJSONTyped,
} from './Team.js';

/**
 * 
 * @export
 * @interface TeamList
 */
export interface TeamList {
    /**
     * 
     * @type {Array<Team>}
     * @memberof TeamList
     */
    items: Array<Team>;
    /**
     * 
     * @type {string}
     * @memberof TeamList
     */
    nextPageToken: string;
}

/**
 * Check if a given object implements the TeamList interface.
 */
export function instanceOfTeamList(value: object): value is TeamList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if ((!('nextPageToken' in value) && !('next_page_token' in value)) || (value['nextPageToken'] === undefined && value['next_page_token'] === undefined)) return false;
    return true;
}

export function TeamListFromJSON(json: any): TeamList {
    return TeamListFromJSONTyped(json, false);
}

export function TeamListFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TeamFromJSON)),
        'nextPageToken': json['next_page_token'],
    };
}

export function TeamListToJSON(json: any): TeamList {
    return TeamListToJSONTyped(json, false);
}

export function TeamListToJSONTyped(value?: TeamList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(TeamToJSON)),
        'next_page_token': value['nextPageToken'],
    };
}

