/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface TeamMembership
 */
export interface TeamMembership {
    /**
     * 
     * @type {string}
     * @memberof TeamMembership
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMembership
     */
    teamId: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMembership
     */
    userId: string;
    /**
     * 
     * @type {boolean}
     * @memberof TeamMembership
     */
    isLead: boolean;
    /**
     * 
     * @type {Date}
     * @memberof TeamMembership
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the TeamMembership interface.
 */
export function instanceOfTeamMembership(value: object): value is TeamMembership {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('teamId' in value) && !('team_id' in value)) || (value['teamId'] === undefined && value['team_id'] === undefined)) return false;
    if ((!('userId' in value) && !('user_id' in value)) || (value['userId'] === undefined && value['user_id'] === undefined)) return false;
    if ((!('isLead' in value) && !('is_lead' in value)) || (value['isLead'] === undefined && value['is_lead'] === undefined)) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    return true;
}

export function TeamMembershipFromJSON(json: any): TeamMembership {
    return TeamMembershipFromJSONTyped(json, false);
}

export function TeamMembershipFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamMembership {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'teamId': json['team_id'],
        'userId': json['user_id'],
        'isLead': json['is_lead'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function TeamMembershipToJSON(json: any): TeamMembership {
    return TeamMembershipToJSONTyped(json, false);
}

export function TeamMembershipToJSONTyped(value?: TeamMembership | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'team_id': value['teamId'],
        'user_id': value['userId'],
        'is_lead': value['isLead'],
        'created_at': value['createdAt'].toISOString(),
    };
}

