/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AgentVersionReachability } from './AgentVersionReachability.js';
import {
    AgentVersionReachabilityFromJSON,
    AgentVersionReachabilityFromJSONTyped,
    AgentVersionReachabilityToJSON,
    AgentVersionReachabilityToJSONTyped,
} from './AgentVersionReachability.js';
import type { AgentVersionStats } from './AgentVersionStats.js';
import {
    AgentVersionStatsFromJSON,
    AgentVersionStatsFromJSONTyped,
    AgentVersionStatsToJSON,
    AgentVersionStatsToJSONTyped,
} from './AgentVersionStats.js';

/**
 * A version from another team's roster, as seen through the public training-grounds listing. reachability (inherited from AgentVersion) is always absent here — matchmaking probe state is internal to the owning team and this endpoint requires no auth.
 * 
 * @export
 * @interface TrainingGroundsVersion
 */
export interface TrainingGroundsVersion {
    /**
     * 
     * @type {string}
     * @memberof TrainingGroundsVersion
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingGroundsVersion
     */
    agentId: string;
    /**
     * Server-derived as "v" + generation. Cannot be set by the client.
     * 
     * @type {string}
     * @memberof TrainingGroundsVersion
     */
    versionLabel: string;
    /**
     * This version's sequence number for its agent, assigned as MAX(generation)+1 at creation — never reused, even if an earlier version is deleted, since match history and ratings still reference it. Nullable only for rows created before this field existed.
     * 
     * @type {number}
     * @memberof TrainingGroundsVersion
     */
    generation?: number | null;
    /**
     * Free-text notes, editable after creation unlike the rest of the version. Console-only: visible to anyone who can see this team, never rendered on the public leaderboard or in match payloads. Do not store secrets here.
     * 
     * @type {string}
     * @memberof TrainingGroundsVersion
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TrainingGroundsVersion
     */
    competitionEligible: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TrainingGroundsVersion
     */
    trainingGroundsEligible: boolean;
    /**
     * HTTPS URL of this version's MCP server. Required before the version is launch-eligible; absent means it cannot yet be dialed for a match.
     * 
     * @type {string}
     * @memberof TrainingGroundsVersion
     */
    mcpEndpointUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TrainingGroundsVersion
     */
    createdAt: Date;
    /**
     * Matchmaking's probe state for this version. Present on team-scoped responses (get/list agent versions, list team agent versions); always absent on the public training-grounds listing (see TrainingGroundsVersion).
     * 
     * @type {AgentVersionReachability}
     * @memberof TrainingGroundsVersion
     */
    reachability?: AgentVersionReachability | null;
    /**
     * Training and competition match record, split by type. Present only on the per-agent version listing (listAgentVersions); absent elsewhere, including the public training-grounds listing.
     * 
     * @type {AgentVersionStats}
     * @memberof TrainingGroundsVersion
     */
    stats?: AgentVersionStats | null;
    /**
     * 
     * @type {string}
     * @memberof TrainingGroundsVersion
     */
    agentName: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingGroundsVersion
     */
    teamName: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingGroundsVersion
     */
    orgName: string;
}

/**
 * Check if a given object implements the TrainingGroundsVersion interface.
 */
export function instanceOfTrainingGroundsVersion(value: object): value is TrainingGroundsVersion {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('agentId' in (value as Record<string, any>)) && !('agent_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['agentId'] === undefined && (value as Record<string, any>)['agent_id'] === undefined)) return false;
    if ((!('versionLabel' in (value as Record<string, any>)) && !('version_label' in (value as Record<string, any>))) || ((value as Record<string, any>)['versionLabel'] === undefined && (value as Record<string, any>)['version_label'] === undefined)) return false;
    if ((!('competitionEligible' in (value as Record<string, any>)) && !('competition_eligible' in (value as Record<string, any>))) || ((value as Record<string, any>)['competitionEligible'] === undefined && (value as Record<string, any>)['competition_eligible'] === undefined)) return false;
    if ((!('trainingGroundsEligible' in (value as Record<string, any>)) && !('training_grounds_eligible' in (value as Record<string, any>))) || ((value as Record<string, any>)['trainingGroundsEligible'] === undefined && (value as Record<string, any>)['training_grounds_eligible'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('agentName' in (value as Record<string, any>)) && !('agent_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['agentName'] === undefined && (value as Record<string, any>)['agent_name'] === undefined)) return false;
    if ((!('teamName' in (value as Record<string, any>)) && !('team_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['teamName'] === undefined && (value as Record<string, any>)['team_name'] === undefined)) return false;
    if ((!('orgName' in (value as Record<string, any>)) && !('org_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgName'] === undefined && (value as Record<string, any>)['org_name'] === undefined)) return false;
    return true;
}

export function TrainingGroundsVersionFromJSON(json: any): TrainingGroundsVersion {
    return TrainingGroundsVersionFromJSONTyped(json, false);
}

export function TrainingGroundsVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainingGroundsVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'agentId': json['agent_id'],
        'versionLabel': json['version_label'],
        'generation': json['generation'] === undefined ? undefined : json['generation'] === null ? null : json['generation'],
        'description': json['description'] == null ? undefined : json['description'],
        'competitionEligible': json['competition_eligible'],
        'trainingGroundsEligible': json['training_grounds_eligible'],
        'mcpEndpointUrl': json['mcp_endpoint_url'] === undefined ? undefined : json['mcp_endpoint_url'] === null ? null : json['mcp_endpoint_url'],
        'createdAt': (new Date(json['created_at'])),
        'reachability': json['reachability'] === undefined ? undefined : json['reachability'] === null ? null : AgentVersionReachabilityFromJSON(json['reachability']),
        'stats': json['stats'] === undefined ? undefined : json['stats'] === null ? null : AgentVersionStatsFromJSON(json['stats']),
        'agentName': json['agent_name'],
        'teamName': json['team_name'],
        'orgName': json['org_name'],
    };
}

export function TrainingGroundsVersionToJSON(json: any): TrainingGroundsVersion {
    return TrainingGroundsVersionToJSONTyped(json, false);
}

export function TrainingGroundsVersionToJSONTyped(value?: TrainingGroundsVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'agent_id': value['agentId'],
        'version_label': value['versionLabel'],
        'generation': value['generation'],
        'description': value['description'],
        'competition_eligible': value['competitionEligible'],
        'training_grounds_eligible': value['trainingGroundsEligible'],
        'mcp_endpoint_url': value['mcpEndpointUrl'],
        'created_at': value['createdAt'].toISOString(),
        'reachability': AgentVersionReachabilityToJSON(value['reachability']),
        'stats': AgentVersionStatsToJSON(value['stats']),
        'agent_name': value['agentName'],
        'team_name': value['teamName'],
        'org_name': value['orgName'],
    };
}

