/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { TrainingGroundsVersion } from './TrainingGroundsVersion.js';
import {
    TrainingGroundsVersionFromJSON,
    TrainingGroundsVersionFromJSONTyped,
    TrainingGroundsVersionToJSON,
    TrainingGroundsVersionToJSONTyped,
} from './TrainingGroundsVersion.js';

/**
 * 
 * @export
 * @interface TrainingGroundsVersionList
 */
export interface TrainingGroundsVersionList {
    /**
     * 
     * @type {Array<TrainingGroundsVersion>}
     * @memberof TrainingGroundsVersionList
     */
    items: Array<TrainingGroundsVersion>;
}

/**
 * Check if a given object implements the TrainingGroundsVersionList interface.
 */
export function instanceOfTrainingGroundsVersionList(value: object): value is TrainingGroundsVersionList {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function TrainingGroundsVersionListFromJSON(json: any): TrainingGroundsVersionList {
    return TrainingGroundsVersionListFromJSONTyped(json, false);
}

export function TrainingGroundsVersionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainingGroundsVersionList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TrainingGroundsVersionFromJSON)),
    };
}

export function TrainingGroundsVersionListToJSON(json: any): TrainingGroundsVersionList {
    return TrainingGroundsVersionListToJSONTyped(json, false);
}

export function TrainingGroundsVersionListToJSONTyped(value?: TrainingGroundsVersionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(TrainingGroundsVersionToJSON)),
    };
}

