/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { UnofficialLeaderboardEntry } from './UnofficialLeaderboardEntry.js';
import {
    UnofficialLeaderboardEntryFromJSON,
    UnofficialLeaderboardEntryFromJSONTyped,
    UnofficialLeaderboardEntryToJSON,
    UnofficialLeaderboardEntryToJSONTyped,
} from './UnofficialLeaderboardEntry.js';

/**
 * 
 * @export
 * @interface UnofficialLeaderboardPage
 */
export interface UnofficialLeaderboardPage {
    /**
     * 
     * @type {Array<UnofficialLeaderboardEntry>}
     * @memberof UnofficialLeaderboardPage
     */
    items: Array<UnofficialLeaderboardEntry>;
    /**
     * 
     * @type {string}
     * @memberof UnofficialLeaderboardPage
     */
    nextPageToken: string;
}

/**
 * Check if a given object implements the UnofficialLeaderboardPage interface.
 */
export function instanceOfUnofficialLeaderboardPage(value: object): value is UnofficialLeaderboardPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if ((!('nextPageToken' in (value as Record<string, any>)) && !('next_page_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextPageToken'] === undefined && (value as Record<string, any>)['next_page_token'] === undefined)) return false;
    return true;
}

export function UnofficialLeaderboardPageFromJSON(json: any): UnofficialLeaderboardPage {
    return UnofficialLeaderboardPageFromJSONTyped(json, false);
}

export function UnofficialLeaderboardPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnofficialLeaderboardPage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(UnofficialLeaderboardEntryFromJSON)),
        'nextPageToken': json['next_page_token'],
    };
}

export function UnofficialLeaderboardPageToJSON(json: any): UnofficialLeaderboardPage {
    return UnofficialLeaderboardPageToJSONTyped(json, false);
}

export function UnofficialLeaderboardPageToJSONTyped(value?: UnofficialLeaderboardPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(UnofficialLeaderboardEntryToJSON)),
        'next_page_token': value['nextPageToken'],
    };
}

