/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UnofficialLeaderboardEntry
 */
export interface UnofficialLeaderboardEntry {
    /**
     * 
     * @type {number}
     * @memberof UnofficialLeaderboardEntry
     */
    rank: number;
    /**
     * 
     * @type {string}
     * @memberof UnofficialLeaderboardEntry
     */
    agentVersionId: string;
    /**
     * 
     * @type {string}
     * @memberof UnofficialLeaderboardEntry
     */
    agentName: string;
    /**
     * 
     * @type {string}
     * @memberof UnofficialLeaderboardEntry
     */
    agentVersionLabel: string;
    /**
     * 
     * @type {string}
     * @memberof UnofficialLeaderboardEntry
     */
    teamName: string;
    /**
     * 
     * @type {string}
     * @memberof UnofficialLeaderboardEntry
     */
    orgName: string;
    /**
     * Glicko-2 rating (r). Default for a new agent-version is 1500.
     * @type {number}
     * @memberof UnofficialLeaderboardEntry
     */
    rating: number;
    /**
     * Glicko-2 rating deviation (RD). Default for a new agent-version is 350.
     * @type {number}
     * @memberof UnofficialLeaderboardEntry
     */
    ratingDeviation: number;
    /**
     * True until enough official matches have narrowed RD.
     * @type {boolean}
     * @memberof UnofficialLeaderboardEntry
     */
    provisional: boolean;
    /**
     * 
     * @type {number}
     * @memberof UnofficialLeaderboardEntry
     */
    wins: number;
    /**
     * 
     * @type {number}
     * @memberof UnofficialLeaderboardEntry
     */
    losses: number;
    /**
     * 
     * @type {number}
     * @memberof UnofficialLeaderboardEntry
     */
    ties: number;
    /**
     * wins / (wins + losses + ties); 0 when no matches have been played.
     * @type {number}
     * @memberof UnofficialLeaderboardEntry
     */
    winRate: number;
    /**
     * (3*wins + ties) / (wins + losses + ties), the ranking key for this board; 0 when no matches have been played. Ranges from 0 to 3.
     * @type {number}
     * @memberof UnofficialLeaderboardEntry
     */
    pointsPerMatch: number;
    /**
     * True when fewer than 5 matches have been played — ranked below all qualified agent-versions, but still shown and scored.
     * @type {boolean}
     * @memberof UnofficialLeaderboardEntry
     */
    provisionalRecord: boolean;
}

/**
 * Check if a given object implements the UnofficialLeaderboardEntry interface.
 */
export function instanceOfUnofficialLeaderboardEntry(value: object): value is UnofficialLeaderboardEntry {
    if (!('rank' in value) || value['rank'] === undefined) return false;
    if ((!('agentVersionId' in (value as Record<string, any>)) && !('agent_version_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['agentVersionId'] === undefined && (value as Record<string, any>)['agent_version_id'] === undefined)) return false;
    if ((!('agentName' in (value as Record<string, any>)) && !('agent_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['agentName'] === undefined && (value as Record<string, any>)['agent_name'] === undefined)) return false;
    if ((!('agentVersionLabel' in (value as Record<string, any>)) && !('agent_version_label' in (value as Record<string, any>))) || ((value as Record<string, any>)['agentVersionLabel'] === undefined && (value as Record<string, any>)['agent_version_label'] === undefined)) return false;
    if ((!('teamName' in (value as Record<string, any>)) && !('team_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['teamName'] === undefined && (value as Record<string, any>)['team_name'] === undefined)) return false;
    if ((!('orgName' in (value as Record<string, any>)) && !('org_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgName'] === undefined && (value as Record<string, any>)['org_name'] === undefined)) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if ((!('ratingDeviation' in (value as Record<string, any>)) && !('rating_deviation' in (value as Record<string, any>))) || ((value as Record<string, any>)['ratingDeviation'] === undefined && (value as Record<string, any>)['rating_deviation'] === undefined)) return false;
    if (!('provisional' in value) || value['provisional'] === undefined) return false;
    if (!('wins' in value) || value['wins'] === undefined) return false;
    if (!('losses' in value) || value['losses'] === undefined) return false;
    if (!('ties' in value) || value['ties'] === undefined) return false;
    if ((!('winRate' in (value as Record<string, any>)) && !('win_rate' in (value as Record<string, any>))) || ((value as Record<string, any>)['winRate'] === undefined && (value as Record<string, any>)['win_rate'] === undefined)) return false;
    if ((!('pointsPerMatch' in (value as Record<string, any>)) && !('points_per_match' in (value as Record<string, any>))) || ((value as Record<string, any>)['pointsPerMatch'] === undefined && (value as Record<string, any>)['points_per_match'] === undefined)) return false;
    if ((!('provisionalRecord' in (value as Record<string, any>)) && !('provisional_record' in (value as Record<string, any>))) || ((value as Record<string, any>)['provisionalRecord'] === undefined && (value as Record<string, any>)['provisional_record'] === undefined)) return false;
    return true;
}

export function UnofficialLeaderboardEntryFromJSON(json: any): UnofficialLeaderboardEntry {
    return UnofficialLeaderboardEntryFromJSONTyped(json, false);
}

export function UnofficialLeaderboardEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnofficialLeaderboardEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'rank': json['rank'],
        'agentVersionId': json['agent_version_id'],
        'agentName': json['agent_name'],
        'agentVersionLabel': json['agent_version_label'],
        'teamName': json['team_name'],
        'orgName': json['org_name'],
        'rating': json['rating'],
        'ratingDeviation': json['rating_deviation'],
        'provisional': json['provisional'],
        'wins': json['wins'],
        'losses': json['losses'],
        'ties': json['ties'],
        'winRate': json['win_rate'],
        'pointsPerMatch': json['points_per_match'],
        'provisionalRecord': json['provisional_record'],
    };
}

export function UnofficialLeaderboardEntryToJSON(json: any): UnofficialLeaderboardEntry {
    return UnofficialLeaderboardEntryToJSONTyped(json, false);
}

export function UnofficialLeaderboardEntryToJSONTyped(value?: UnofficialLeaderboardEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rank': value['rank'],
        'agent_version_id': value['agentVersionId'],
        'agent_name': value['agentName'],
        'agent_version_label': value['agentVersionLabel'],
        'team_name': value['teamName'],
        'org_name': value['orgName'],
        'rating': value['rating'],
        'rating_deviation': value['ratingDeviation'],
        'provisional': value['provisional'],
        'wins': value['wins'],
        'losses': value['losses'],
        'ties': value['ties'],
        'win_rate': value['winRate'],
        'points_per_match': value['pointsPerMatch'],
        'provisional_record': value['provisionalRecord'],
    };
}

