/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpdateAgentRequest
 */
export interface UpdateAgentRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the UpdateAgentRequest interface.
 */
export function instanceOfUpdateAgentRequest(value: object): value is UpdateAgentRequest {
    return true;
}

export function UpdateAgentRequestFromJSON(json: any): UpdateAgentRequest {
    return UpdateAgentRequestFromJSONTyped(json, false);
}

export function UpdateAgentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAgentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UpdateAgentRequestToJSON(json: any): UpdateAgentRequest {
    return UpdateAgentRequestToJSONTyped(json, false);
}

export function UpdateAgentRequestToJSONTyped(value?: UpdateAgentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

