/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpdateAgentVersionRequest
 */
export interface UpdateAgentVersionRequest {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateAgentVersionRequest
     */
    competitionEligible?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateAgentVersionRequest
     */
    trainingGroundsEligible?: boolean;
}

/**
 * Check if a given object implements the UpdateAgentVersionRequest interface.
 */
export function instanceOfUpdateAgentVersionRequest(value: object): value is UpdateAgentVersionRequest {
    return true;
}

export function UpdateAgentVersionRequestFromJSON(json: any): UpdateAgentVersionRequest {
    return UpdateAgentVersionRequestFromJSONTyped(json, false);
}

export function UpdateAgentVersionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAgentVersionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'competitionEligible': json['competition_eligible'] == null ? undefined : json['competition_eligible'],
        'trainingGroundsEligible': json['training_grounds_eligible'] == null ? undefined : json['training_grounds_eligible'],
    };
}

export function UpdateAgentVersionRequestToJSON(json: any): UpdateAgentVersionRequest {
    return UpdateAgentVersionRequestToJSONTyped(json, false);
}

export function UpdateAgentVersionRequestToJSONTyped(value?: UpdateAgentVersionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'competition_eligible': value['competitionEligible'],
        'training_grounds_eligible': value['trainingGroundsEligible'],
    };
}

