/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpdateTeamRequest
 */
export interface UpdateTeamRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateTeamRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTeamRequest
     */
    logoUrl?: string;
}

/**
 * Check if a given object implements the UpdateTeamRequest interface.
 */
export function instanceOfUpdateTeamRequest(value: object): value is UpdateTeamRequest {
    return true;
}

export function UpdateTeamRequestFromJSON(json: any): UpdateTeamRequest {
    return UpdateTeamRequestFromJSONTyped(json, false);
}

export function UpdateTeamRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTeamRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'logoUrl': json['logo_url'] == null ? undefined : json['logo_url'],
    };
}

export function UpdateTeamRequestToJSON(json: any): UpdateTeamRequest {
    return UpdateTeamRequestToJSONTyped(json, false);
}

export function UpdateTeamRequestToJSONTyped(value?: UpdateTeamRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'logo_url': value['logoUrl'],
    };
}

