/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type AgentVersion,
    AgentVersionFromJSON,
    AgentVersionToJSON,
} from '../models/AgentVersion.js';
import {
    type AgentVersionCreated,
    AgentVersionCreatedFromJSON,
    AgentVersionCreatedToJSON,
} from '../models/AgentVersionCreated.js';
import {
    type AgentVersionKeyRotated,
    AgentVersionKeyRotatedFromJSON,
    AgentVersionKeyRotatedToJSON,
} from '../models/AgentVersionKeyRotated.js';
import {
    type CreateAgentVersionRequest,
    CreateAgentVersionRequestFromJSON,
    CreateAgentVersionRequestToJSON,
} from '../models/CreateAgentVersionRequest.js';
import {
    type UpdateAgentVersionRequest,
    UpdateAgentVersionRequestFromJSON,
    UpdateAgentVersionRequestToJSON,
} from '../models/UpdateAgentVersionRequest.js';

export interface CreateAgentVersionOperationRequest {
    id: string;
    createAgentVersionRequest: CreateAgentVersionRequest;
    idempotencyKey?: string;
}

export interface GetAgentVersionRequest {
    id: string;
}

export interface RotateAgentVersionKeyRequest {
    id: string;
    idempotencyKey?: string;
}

export interface UpdateAgentVersionOperationRequest {
    id: string;
    updateAgentVersionRequest: UpdateAgentVersionRequest;
}

/**
 * 
 */
export class AgentVersionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createAgentVersion without sending the request
     */
    async createAgentVersionRequestOpts(requestParameters: CreateAgentVersionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createAgentVersion().'
            );
        }

        if (requestParameters['createAgentVersionRequest'] == null) {
            throw new runtime.RequiredError(
                'createAgentVersionRequest',
                'Required parameter "createAgentVersionRequest" was null or undefined when calling createAgentVersion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/agents/{id}/versions`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAgentVersionRequestToJSON(requestParameters['createAgentVersionRequest']),
        };
    }

    /**
     */
    async createAgentVersionRaw(requestParameters: CreateAgentVersionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentVersionCreated>> {
        const requestOptions = await this.createAgentVersionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentVersionCreatedFromJSON(jsonValue));
    }

    /**
     */
    async createAgentVersion(requestParameters: CreateAgentVersionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentVersionCreated> {
        const response = await this.createAgentVersionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAgentVersion without sending the request
     */
    async getAgentVersionRequestOpts(requestParameters: GetAgentVersionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAgentVersion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/agent-versions/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAgentVersionRaw(requestParameters: GetAgentVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentVersion>> {
        const requestOptions = await this.getAgentVersionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentVersionFromJSON(jsonValue));
    }

    /**
     */
    async getAgentVersion(requestParameters: GetAgentVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentVersion> {
        const response = await this.getAgentVersionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rotateAgentVersionKey without sending the request
     */
    async rotateAgentVersionKeyRequestOpts(requestParameters: RotateAgentVersionKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling rotateAgentVersionKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/agent-versions/{id}/rotate-key`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Issue a new per-agent-version MCP auth key, distinct from this API\'s own bearer credential 
     */
    async rotateAgentVersionKeyRaw(requestParameters: RotateAgentVersionKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentVersionKeyRotated>> {
        const requestOptions = await this.rotateAgentVersionKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentVersionKeyRotatedFromJSON(jsonValue));
    }

    /**
     * Issue a new per-agent-version MCP auth key, distinct from this API\'s own bearer credential 
     */
    async rotateAgentVersionKey(requestParameters: RotateAgentVersionKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentVersionKeyRotated> {
        const response = await this.rotateAgentVersionKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateAgentVersion without sending the request
     */
    async updateAgentVersionRequestOpts(requestParameters: UpdateAgentVersionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateAgentVersion().'
            );
        }

        if (requestParameters['updateAgentVersionRequest'] == null) {
            throw new runtime.RequiredError(
                'updateAgentVersionRequest',
                'Required parameter "updateAgentVersionRequest" was null or undefined when calling updateAgentVersion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/agent-versions/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAgentVersionRequestToJSON(requestParameters['updateAgentVersionRequest']),
        };
    }

    /**
     * Update mutable fields, notably competition_eligible and training_grounds_eligible 
     */
    async updateAgentVersionRaw(requestParameters: UpdateAgentVersionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentVersion>> {
        const requestOptions = await this.updateAgentVersionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentVersionFromJSON(jsonValue));
    }

    /**
     * Update mutable fields, notably competition_eligible and training_grounds_eligible 
     */
    async updateAgentVersion(requestParameters: UpdateAgentVersionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentVersion> {
        const response = await this.updateAgentVersionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
