/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type AgentVersion,
    AgentVersionFromJSON,
    AgentVersionToJSON,
} from '../models/AgentVersion.js';
import {
    type AgentVersionCreated,
    AgentVersionCreatedFromJSON,
    AgentVersionCreatedToJSON,
} from '../models/AgentVersionCreated.js';
import {
    type AgentVersionKeyRotated,
    AgentVersionKeyRotatedFromJSON,
    AgentVersionKeyRotatedToJSON,
} from '../models/AgentVersionKeyRotated.js';
import {
    type AgentVersionList,
    AgentVersionListFromJSON,
    AgentVersionListToJSON,
} from '../models/AgentVersionList.js';
import {
    type CreateAgentVersionRequest,
    CreateAgentVersionRequestFromJSON,
    CreateAgentVersionRequestToJSON,
} from '../models/CreateAgentVersionRequest.js';
import {
    type TeamAgentVersionList,
    TeamAgentVersionListFromJSON,
    TeamAgentVersionListToJSON,
} from '../models/TeamAgentVersionList.js';
import {
    type TrainingGroundsVersionList,
    TrainingGroundsVersionListFromJSON,
    TrainingGroundsVersionListToJSON,
} from '../models/TrainingGroundsVersionList.js';
import {
    type UpdateAgentVersionRequest,
    UpdateAgentVersionRequestFromJSON,
    UpdateAgentVersionRequestToJSON,
} from '../models/UpdateAgentVersionRequest.js';

export interface CreateAgentVersionOperationRequest {
    id: string;
    createAgentVersionRequest: CreateAgentVersionRequest;
    idempotencyKey?: string;
}

export interface DeleteAgentVersionRequest {
    id: string;
}

export interface GetAgentVersionRequest {
    id: string;
}

export interface ListAgentVersionsRequest {
    id: string;
}

export interface ListTeamAgentVersionsRequest {
    teamId: string;
}

export interface ListTrainingGroundsVersionsRequest {
    trainingGroundsEligible: ListTrainingGroundsVersionsTrainingGroundsEligibleEnum;
}

export interface RotateAgentVersionKeyRequest {
    id: string;
    idempotencyKey?: string;
}

export interface UpdateAgentVersionOperationRequest {
    id: string;
    updateAgentVersionRequest: UpdateAgentVersionRequest;
}

/**
 * 
 */
export class AgentVersionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createAgentVersion without sending the request
     */
    async createAgentVersionRequestOpts(requestParameters: CreateAgentVersionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createAgentVersion().'
            );
        }

        if (requestParameters['createAgentVersionRequest'] == null) {
            throw new runtime.RequiredError(
                'createAgentVersionRequest',
                'Required parameter "createAgentVersionRequest" was null or undefined when calling createAgentVersion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/agents/{id}/versions`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAgentVersionRequestToJSON(requestParameters['createAgentVersionRequest']),
        };
    }

    /**
     */
    async createAgentVersionRaw(requestParameters: CreateAgentVersionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentVersionCreated>> {
        const requestOptions = await this.createAgentVersionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentVersionCreatedFromJSON(jsonValue));
    }

    /**
     */
    async createAgentVersion(requestParameters: CreateAgentVersionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentVersionCreated> {
        const response = await this.createAgentVersionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteAgentVersion without sending the request
     */
    async deleteAgentVersionRequestOpts(requestParameters: DeleteAgentVersionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteAgentVersion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/agent-versions/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Refuses with 409 if the version has any matches row at all — training or competition, regardless of status. The parent agent and its other versions are unaffected. 
     * Delete a single agent version that has never been used
     */
    async deleteAgentVersionRaw(requestParameters: DeleteAgentVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteAgentVersionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Refuses with 409 if the version has any matches row at all — training or competition, regardless of status. The parent agent and its other versions are unaffected. 
     * Delete a single agent version that has never been used
     */
    async deleteAgentVersion(requestParameters: DeleteAgentVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteAgentVersionRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAgentVersion without sending the request
     */
    async getAgentVersionRequestOpts(requestParameters: GetAgentVersionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAgentVersion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/agent-versions/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAgentVersionRaw(requestParameters: GetAgentVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentVersion>> {
        const requestOptions = await this.getAgentVersionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentVersionFromJSON(jsonValue));
    }

    /**
     */
    async getAgentVersion(requestParameters: GetAgentVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentVersion> {
        const response = await this.getAgentVersionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAgentVersions without sending the request
     */
    async listAgentVersionsRequestOpts(requestParameters: ListAgentVersionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listAgentVersions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/agents/{id}/versions`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Team-scoped read — any member of the owning team, or its Lead/org Admin/Owner, may list it. Powers the launch UI\'s \"pick one of my own agent\'s versions\" step. 
     * List one agent\'s versions
     */
    async listAgentVersionsRaw(requestParameters: ListAgentVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentVersionList>> {
        const requestOptions = await this.listAgentVersionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentVersionListFromJSON(jsonValue));
    }

    /**
     * Team-scoped read — any member of the owning team, or its Lead/org Admin/Owner, may list it. Powers the launch UI\'s \"pick one of my own agent\'s versions\" step. 
     * List one agent\'s versions
     */
    async listAgentVersions(requestParameters: ListAgentVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentVersionList> {
        const response = await this.listAgentVersionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTeamAgentVersions without sending the request
     */
    async listTeamAgentVersionsRequestOpts(requestParameters: ListTeamAgentVersionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling listTeamAgentVersions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{teamId}/agent-versions`;
        urlPath = urlPath.replace('{teamId}', encodeURIComponent(String(requestParameters['teamId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Team-scoped read — any member of the owning team, or its Lead/org Admin/Owner, may list it. Flattens the agent → version cascade into one listing, powering the launch UI\'s \"Your agent\" picker with the same single-dropdown shape listTrainingGroundsVersions gives the opponent picker. 
     * List every version across all of a team\'s agents
     */
    async listTeamAgentVersionsRaw(requestParameters: ListTeamAgentVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamAgentVersionList>> {
        const requestOptions = await this.listTeamAgentVersionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamAgentVersionListFromJSON(jsonValue));
    }

    /**
     * Team-scoped read — any member of the owning team, or its Lead/org Admin/Owner, may list it. Flattens the agent → version cascade into one listing, powering the launch UI\'s \"Your agent\" picker with the same single-dropdown shape listTrainingGroundsVersions gives the opponent picker. 
     * List every version across all of a team\'s agents
     */
    async listTeamAgentVersions(requestParameters: ListTeamAgentVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamAgentVersionList> {
        const response = await this.listTeamAgentVersionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTrainingGroundsVersions without sending the request
     */
    async listTrainingGroundsVersionsRequestOpts(requestParameters: ListTrainingGroundsVersionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['trainingGroundsEligible'] == null) {
            throw new runtime.RequiredError(
                'trainingGroundsEligible',
                'Required parameter "trainingGroundsEligible" was null or undefined when calling listTrainingGroundsVersions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['trainingGroundsEligible'] != null) {
            queryParameters['training_grounds_eligible'] = requestParameters['trainingGroundsEligible'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/agent-versions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Public, cross-team listing for the Training Grounds opponent picker. Only versions with both training_grounds_eligible=true and a registered mcp_endpoint_url are returned — an endpoint-less version isn\'t dialable and so isn\'t a legal opponent regardless of its eligibility flag. training_grounds_eligible=true is currently the only accepted value for the query parameter. 
     * Discover training-grounds-eligible opponents
     */
    async listTrainingGroundsVersionsRaw(requestParameters: ListTrainingGroundsVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingGroundsVersionList>> {
        const requestOptions = await this.listTrainingGroundsVersionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingGroundsVersionListFromJSON(jsonValue));
    }

    /**
     * Public, cross-team listing for the Training Grounds opponent picker. Only versions with both training_grounds_eligible=true and a registered mcp_endpoint_url are returned — an endpoint-less version isn\'t dialable and so isn\'t a legal opponent regardless of its eligibility flag. training_grounds_eligible=true is currently the only accepted value for the query parameter. 
     * Discover training-grounds-eligible opponents
     */
    async listTrainingGroundsVersions(requestParameters: ListTrainingGroundsVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingGroundsVersionList> {
        const response = await this.listTrainingGroundsVersionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rotateAgentVersionKey without sending the request
     */
    async rotateAgentVersionKeyRequestOpts(requestParameters: RotateAgentVersionKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling rotateAgentVersionKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/agent-versions/{id}/rotate-key`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Issue a new per-agent-version MCP auth key, distinct from this API\'s own bearer credential 
     */
    async rotateAgentVersionKeyRaw(requestParameters: RotateAgentVersionKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentVersionKeyRotated>> {
        const requestOptions = await this.rotateAgentVersionKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentVersionKeyRotatedFromJSON(jsonValue));
    }

    /**
     * Issue a new per-agent-version MCP auth key, distinct from this API\'s own bearer credential 
     */
    async rotateAgentVersionKey(requestParameters: RotateAgentVersionKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentVersionKeyRotated> {
        const response = await this.rotateAgentVersionKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateAgentVersion without sending the request
     */
    async updateAgentVersionRequestOpts(requestParameters: UpdateAgentVersionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateAgentVersion().'
            );
        }

        if (requestParameters['updateAgentVersionRequest'] == null) {
            throw new runtime.RequiredError(
                'updateAgentVersionRequest',
                'Required parameter "updateAgentVersionRequest" was null or undefined when calling updateAgentVersion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/agent-versions/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAgentVersionRequestToJSON(requestParameters['updateAgentVersionRequest']),
        };
    }

    /**
     * Update mutable fields, notably competition_eligible and training_grounds_eligible 
     */
    async updateAgentVersionRaw(requestParameters: UpdateAgentVersionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentVersion>> {
        const requestOptions = await this.updateAgentVersionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentVersionFromJSON(jsonValue));
    }

    /**
     * Update mutable fields, notably competition_eligible and training_grounds_eligible 
     */
    async updateAgentVersion(requestParameters: UpdateAgentVersionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentVersion> {
        const response = await this.updateAgentVersionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum ListTrainingGroundsVersionsTrainingGroundsEligibleEnum {
    True = 'true'
}
