/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';

export interface DownloadCommandLogRequest {
    id: string;
}

/**
 * 
 */
export class CommandLogsApi extends runtime.BaseAPI {

    /**
     * Creates request options for downloadCommandLog without sending the request
     */
    async downloadCommandLogRequestOpts(requestParameters: DownloadCommandLogRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling downloadCommandLog().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/matches/{id}/log`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Streamed newline-delimited JSON per playback-and-replay.md#command-log-format-json-lines: one Match Header record, one Impulse record per line, one Outcome record. 
     * Download a completed match\'s command log
     */
    async downloadCommandLogRaw(requestParameters: DownloadCommandLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.downloadCommandLogRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Streamed newline-delimited JSON per playback-and-replay.md#command-log-format-json-lines: one Match Header record, one Impulse record per line, one Outcome record. 
     * Download a completed match\'s command log
     */
    async downloadCommandLog(requestParameters: DownloadCommandLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadCommandLogRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
