/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';

export interface GetMatchLogRequest {
    id: string;
    download?: GetMatchLogDownloadEnum;
}

/**
 * 
 */
export class CommandLogsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getMatchLog without sending the request
     */
    async getMatchLogRequestOpts(requestParameters: GetMatchLogRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getMatchLog().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['download'] != null) {
            queryParameters['download'] = requestParameters['download'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/matches/{id}/log`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The command log recorded for this match, as a single JSON document (Match Header, the full Impulse list, and Outcome). This is an interim representation of the format defined in playback-and-replay.md#command-log-format-json-lines; that document\'s per-record JSON Lines transport (application/x-ndjson, streamed one record per line) is this endpoint\'s target shape and lands in a later release — see playback-and-replay.md#download-endpoint. 404 if the match does not exist or has no ingested log yet. A plain GET (used by the console\'s replay view) always succeeds regardless of the match\'s `log_downloadable` flag. Passing `download=1` marks the request as an explicit download rather than replay; for a match with `log_downloadable=false` that variant alone returns 403. This lets one specific match\'s log be exempted from bulk download without breaking its own replay. 
     * Get a completed match\'s command log
     */
    async getMatchLogRaw(requestParameters: GetMatchLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.getMatchLogRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * The command log recorded for this match, as a single JSON document (Match Header, the full Impulse list, and Outcome). This is an interim representation of the format defined in playback-and-replay.md#command-log-format-json-lines; that document\'s per-record JSON Lines transport (application/x-ndjson, streamed one record per line) is this endpoint\'s target shape and lands in a later release — see playback-and-replay.md#download-endpoint. 404 if the match does not exist or has no ingested log yet. A plain GET (used by the console\'s replay view) always succeeds regardless of the match\'s `log_downloadable` flag. Passing `download=1` marks the request as an explicit download rather than replay; for a match with `log_downloadable=false` that variant alone returns 403. This lets one specific match\'s log be exempted from bulk download without breaking its own replay. 
     * Get a completed match\'s command log
     */
    async getMatchLog(requestParameters: GetMatchLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getMatchLogRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum GetMatchLogDownloadEnum {
    _1 = '1'
}
