/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type Dispute,
    DisputeFromJSON,
    DisputeToJSON,
} from '../models/Dispute.js';
import {
    type DisputeList,
    DisputeListFromJSON,
    DisputeListToJSON,
} from '../models/DisputeList.js';
import {
    type FileDisputeRequest,
    FileDisputeRequestFromJSON,
    FileDisputeRequestToJSON,
} from '../models/FileDisputeRequest.js';

export interface FileDisputeOperationRequest {
    id: string;
    fileDisputeRequest: FileDisputeRequest;
    idempotencyKey?: string;
}

export interface ListDisputesRequest {
    id: string;
    pageSize?: number;
    pageToken?: string;
}

/**
 * 
 */
export class DisputesApi extends runtime.BaseAPI {

    /**
     * Creates request options for fileDispute without sending the request
     */
    async fileDisputeRequestOpts(requestParameters: FileDisputeOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling fileDispute().'
            );
        }

        if (requestParameters['fileDisputeRequest'] == null) {
            throw new runtime.RequiredError(
                'fileDisputeRequest',
                'Required parameter "fileDisputeRequest" was null or undefined when calling fileDispute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/matches/{id}/disputes`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FileDisputeRequestToJSON(requestParameters['fileDisputeRequest']),
        };
    }

    /**
     * File a dispute as a member of a participating team
     */
    async fileDisputeRaw(requestParameters: FileDisputeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dispute>> {
        const requestOptions = await this.fileDisputeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DisputeFromJSON(jsonValue));
    }

    /**
     * File a dispute as a member of a participating team
     */
    async fileDispute(requestParameters: FileDisputeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dispute> {
        const response = await this.fileDisputeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listDisputes without sending the request
     */
    async listDisputesRequestOpts(requestParameters: ListDisputesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listDisputes().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/matches/{id}/disputes`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listDisputesRaw(requestParameters: ListDisputesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DisputeList>> {
        const requestOptions = await this.listDisputesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DisputeListFromJSON(jsonValue));
    }

    /**
     */
    async listDisputes(requestParameters: ListDisputesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DisputeList> {
        const response = await this.listDisputesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
