/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type HistoricLeaderboardPage,
    HistoricLeaderboardPageFromJSON,
    HistoricLeaderboardPageToJSON,
} from '../models/HistoricLeaderboardPage.js';
import {
    type LeaderboardPage,
    LeaderboardPageFromJSON,
    LeaderboardPageToJSON,
} from '../models/LeaderboardPage.js';

export interface GetHistoricLeaderboardRequest {
    pageSize?: number;
    pageToken?: string;
}

export interface GetOfficialLeaderboardRequest {
    pageSize?: number;
    pageToken?: string;
}

export interface GetOrganizationLeaderboardRequest {
    view?: GetOrganizationLeaderboardViewEnum;
    pageSize?: number;
    pageToken?: string;
}

export interface GetUnofficialLeaderboardRequest {
    pageSize?: number;
    pageToken?: string;
}

/**
 * 
 */
export class LeaderboardsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getHistoricLeaderboard without sending the request
     */
    async getHistoricLeaderboardRequestOpts(requestParameters: GetHistoricLeaderboardRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/leaderboards/historic`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getHistoricLeaderboardRaw(requestParameters: GetHistoricLeaderboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HistoricLeaderboardPage>> {
        const requestOptions = await this.getHistoricLeaderboardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HistoricLeaderboardPageFromJSON(jsonValue));
    }

    /**
     */
    async getHistoricLeaderboard(requestParameters: GetHistoricLeaderboardRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HistoricLeaderboardPage> {
        const response = await this.getHistoricLeaderboardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOfficialLeaderboard without sending the request
     */
    async getOfficialLeaderboardRequestOpts(requestParameters: GetOfficialLeaderboardRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/leaderboards/official`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getOfficialLeaderboardRaw(requestParameters: GetOfficialLeaderboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeaderboardPage>> {
        const requestOptions = await this.getOfficialLeaderboardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LeaderboardPageFromJSON(jsonValue));
    }

    /**
     */
    async getOfficialLeaderboard(requestParameters: GetOfficialLeaderboardRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeaderboardPage> {
        const response = await this.getOfficialLeaderboardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOrganizationLeaderboard without sending the request
     */
    async getOrganizationLeaderboardRequestOpts(requestParameters: GetOrganizationLeaderboardRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['view'] != null) {
            queryParameters['view'] = requestParameters['view'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/leaderboards/organizations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getOrganizationLeaderboardRaw(requestParameters: GetOrganizationLeaderboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeaderboardPage>> {
        const requestOptions = await this.getOrganizationLeaderboardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LeaderboardPageFromJSON(jsonValue));
    }

    /**
     */
    async getOrganizationLeaderboard(requestParameters: GetOrganizationLeaderboardRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeaderboardPage> {
        const response = await this.getOrganizationLeaderboardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUnofficialLeaderboard without sending the request
     */
    async getUnofficialLeaderboardRequestOpts(requestParameters: GetUnofficialLeaderboardRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/leaderboards/unofficial`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getUnofficialLeaderboardRaw(requestParameters: GetUnofficialLeaderboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeaderboardPage>> {
        const requestOptions = await this.getUnofficialLeaderboardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LeaderboardPageFromJSON(jsonValue));
    }

    /**
     */
    async getUnofficialLeaderboard(requestParameters: GetUnofficialLeaderboardRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeaderboardPage> {
        const response = await this.getUnofficialLeaderboardRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum GetOrganizationLeaderboardViewEnum {
    TopPerOrg = 'top-per-org',
    AllAgents = 'all-agents'
}
