/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type LaunchMatchRequest,
    LaunchMatchRequestFromJSON,
    LaunchMatchRequestToJSON,
} from '../models/LaunchMatchRequest.js';
import {
    type Match,
    MatchFromJSON,
    MatchToJSON,
} from '../models/Match.js';
import {
    type MatchLaunched,
    MatchLaunchedFromJSON,
    MatchLaunchedToJSON,
} from '../models/MatchLaunched.js';
import {
    type MatchList,
    MatchListFromJSON,
    MatchListToJSON,
} from '../models/MatchList.js';

export interface GetMatchRequest {
    id: string;
}

export interface LaunchMatchOperationRequest {
    launchMatchRequest: LaunchMatchRequest;
    idempotencyKey?: string;
}

export interface ListMatchesRequest {
    pageSize?: number;
    pageToken?: string;
    agentId?: string;
    teamId?: string;
    orgId?: string;
    matchType?: string;
    status?: string;
}

/**
 * 
 */
export class MatchesApi extends runtime.BaseAPI {

    /**
     * Creates request options for getMatch without sending the request
     */
    async getMatchRequestOpts(requestParameters: GetMatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getMatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/matches/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getMatchRaw(requestParameters: GetMatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Match>> {
        const requestOptions = await this.getMatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MatchFromJSON(jsonValue));
    }

    /**
     */
    async getMatch(requestParameters: GetMatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Match> {
        const response = await this.getMatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for launchMatch without sending the request
     */
    async launchMatchRequestOpts(requestParameters: LaunchMatchOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['launchMatchRequest'] == null) {
            throw new runtime.RequiredError(
                'launchMatchRequest',
                'Required parameter "launchMatchRequest" was null or undefined when calling launchMatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/matches`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LaunchMatchRequestToJSON(requestParameters['launchMatchRequest']),
        };
    }

    /**
     * Starts a match in-process immediately — there is no \"pending\" state, so a successful response always reports status=running. The acting team is the challenger agent-version\'s own owning team: a Member may only launch with a version they personally registered, matching the registrant enforcement already applied to agent-version writes. The opponent must be training_grounds_eligible and, like the challenger, must have a registered mcp_endpoint_url. match_type is always forced to \"training\"; scenario_id is not yet supported and must be omitted. 
     * Launch a Training Grounds match
     */
    async launchMatchRaw(requestParameters: LaunchMatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MatchLaunched>> {
        const requestOptions = await this.launchMatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MatchLaunchedFromJSON(jsonValue));
    }

    /**
     * Starts a match in-process immediately — there is no \"pending\" state, so a successful response always reports status=running. The acting team is the challenger agent-version\'s own owning team: a Member may only launch with a version they personally registered, matching the registrant enforcement already applied to agent-version writes. The opponent must be training_grounds_eligible and, like the challenger, must have a registered mcp_endpoint_url. match_type is always forced to \"training\"; scenario_id is not yet supported and must be omitted. 
     * Launch a Training Grounds match
     */
    async launchMatch(requestParameters: LaunchMatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MatchLaunched> {
        const response = await this.launchMatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listMatches without sending the request
     */
    async listMatchesRequestOpts(requestParameters: ListMatchesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        if (requestParameters['agentId'] != null) {
            queryParameters['agent_id'] = requestParameters['agentId'];
        }

        if (requestParameters['teamId'] != null) {
            queryParameters['team_id'] = requestParameters['teamId'];
        }

        if (requestParameters['orgId'] != null) {
            queryParameters['org_id'] = requestParameters['orgId'];
        }

        if (requestParameters['matchType'] != null) {
            queryParameters['match_type'] = requestParameters['matchType'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/matches`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listMatchesRaw(requestParameters: ListMatchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MatchList>> {
        const requestOptions = await this.listMatchesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MatchListFromJSON(jsonValue));
    }

    /**
     */
    async listMatches(requestParameters: ListMatchesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MatchList> {
        const response = await this.listMatchesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
