/* tslint:disable */
/* eslint-disable */
/**
 * Gismo Control-Plane API
 * REST interface for organizations, users, teams, agents, agent-versions, matches, leaderboards, and disputes. Source of truth: specs/2026/control-plane-api.md in gismo-platform. Live match play runs over MCP, described separately by mcp-schema/_*.json — not this document. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type CreateTokenRequest,
    CreateTokenRequestFromJSON,
    CreateTokenRequestToJSON,
} from '../models/CreateTokenRequest.js';
import {
    type PersonalApiTokenCreated,
    PersonalApiTokenCreatedFromJSON,
    PersonalApiTokenCreatedToJSON,
} from '../models/PersonalApiTokenCreated.js';
import {
    type PersonalApiTokenList,
    PersonalApiTokenListFromJSON,
    PersonalApiTokenListToJSON,
} from '../models/PersonalApiTokenList.js';

export interface CreateTokenOperationRequest {
    createTokenRequest: CreateTokenRequest;
    idempotencyKey?: string;
}

export interface ListTokensRequest {
    pageSize?: number;
    pageToken?: string;
}

export interface RevokeTokenRequest {
    id: string;
}

/**
 * 
 */
export class PersonalAPITokensApi extends runtime.BaseAPI {

    /**
     * Creates request options for createToken without sending the request
     */
    async createTokenRequestOpts(requestParameters: CreateTokenOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createTokenRequest'] == null) {
            throw new runtime.RequiredError(
                'createTokenRequest',
                'Required parameter "createTokenRequest" was null or undefined when calling createToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/tokens`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTokenRequestToJSON(requestParameters['createTokenRequest']),
        };
    }

    /**
     * Requires a Clerk JWT session; a PAT cannot be used to mint another PAT. The raw token value is returned once and never again. 
     * Mint a Personal API Token scoped to one team
     */
    async createTokenRaw(requestParameters: CreateTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonalApiTokenCreated>> {
        const requestOptions = await this.createTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonalApiTokenCreatedFromJSON(jsonValue));
    }

    /**
     * Requires a Clerk JWT session; a PAT cannot be used to mint another PAT. The raw token value is returned once and never again. 
     * Mint a Personal API Token scoped to one team
     */
    async createToken(requestParameters: CreateTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonalApiTokenCreated> {
        const response = await this.createTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTokens without sending the request
     */
    async listTokensRequestOpts(requestParameters: ListTokensRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/tokens`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the caller\'s own Personal API Tokens
     */
    async listTokensRaw(requestParameters: ListTokensRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonalApiTokenList>> {
        const requestOptions = await this.listTokensRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonalApiTokenListFromJSON(jsonValue));
    }

    /**
     * List the caller\'s own Personal API Tokens
     */
    async listTokens(requestParameters: ListTokensRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonalApiTokenList> {
        const response = await this.listTokensRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokeToken without sending the request
     */
    async revokeTokenRequestOpts(requestParameters: RevokeTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling revokeToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/tokens/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Revoke a Personal API Token
     */
    async revokeTokenRaw(requestParameters: RevokeTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.revokeTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Revoke a Personal API Token
     */
    async revokeToken(requestParameters: RevokeTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.revokeTokenRaw(requestParameters, initOverrides);
    }

}
